### ISSUE TITLE
[bug]: 2024-07-09 21:26:10.034 [ERR] RPCS: [/taprpc.TaprootAssets/ListAssets]: unable to marshal asset: unable to extract decimal display for asset_id=dc68dcc370f15f3c318cc947e0315ad849a75cfb3ad6ef177933a8873d7dfe25 :decimal display field missing

### ISSUE THREAD

**Issue by weltitob** [lightninglabs/taproot-assets#1001]
Cant really explain myself this error it occurs on version  lightninglabs/lightning-terminal:v0.13.2-alpha.rc2 when importing my .tapd folder and thus my assets: 2024-07-09 21:26:10.034 [ERR] RPCS: [/taprpc.TaprootAssets/ListAssets]: unable to marshal asset: unable to extract decimal display for asset_id=dc68dcc370f15f3c318cc947e0315ad849a75cfb3ad6ef177933a8873d7dfe25 :decimal display field missing

**Comment by Roasbeef** [comment]
Looks like the culprit is here: https://github.com/lightninglabs/taproot-assets/blob/aa3d671f4bc4b7e14c44e4e172011d3740065bd3/proof/meta.go#L236-L240

Will have a fix up shortly.

**Comment by Roasbeef** [comment]
This'll be fixed by https://github.com/lightninglabs/taproot-assets/pull/998
