### ISSUE TITLE
tapchannel/[feature]: update `AuxInvoiceManager` to enforce strict forwarding for invoices

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#1008]
**Is your feature request related to a problem? Please describe.**

Today if a user has one private asset channel, and a public Bitcoin channel, then due to fees or jitter otherwise, a sender may actually pay over the _BTC_ channel. From the receivers side, the invoice _has_ been paid, but potentially not in the desired currency. 

**Describe the solution you'd like**

Today we'll based the custom invoice hook based on if an HTLC has custom data or not: https://github.com/lightninglabs/taproot-assets/blob/fca9d11f027cdb5b81a36c4a8999c6b010ac0c44/tapchannel/aux_invoice_manager.go#L121-L124. 

We should also do the opposite check: if we get an HTLC over a channel, for an invoice with custom data, but the HTLC has no custom data, then we reject. 

**Describe alternatives you've considered**

Make the behavior above optional, all a lax receive mode (any currency works). 

>

**Comment by dstadulis** [comment]
>[should] reject the invoice if it doesn't come across the asset chan we expect
>logic would be in the invoice acceptor

Handles the case where an external node attempts to route payment to node ID rather than over a discrete set of SCIDs

**Comment by guggero** [comment]
Probably also need to do something similar on the `SendPayment` side.
Example for paying a 500 sat invoice with assets, but the pathfinding choosing arbitrary (non-TAP channel) first hops:

```
d5fac4f7358e:/# litcli --macaroonpath /root/.lnd/data/chain/bitcoin/mainnet/admin.macaroon ln payinvoice --pay_req lnbc5u1pnvgudppp52g3pn35s5ewzu2guahyv44mparkxg2y7r3egqpflumc6yt5xdd8sdqqcqzzsxqyz5vqsp5w64str3ac0s4z6h4fhzry5gcj483mvlz8n5l6uajcfsl2uvscvys9qxpqysgqwmw58axr96xln4srf4wgp69aqkrfgfl7cv79h83cs56s6zke07yhmr672xeyj8e6sz4k0w45dhcw559mtu5k3vwkv35dw6sk0qqlkugpjwcrpf --asset_id d75dae162be7cd0a2df76831ee1cce4eaeb74a32fabb0d46be7a0ad70fd6ad27
Payment hash: 522219c690a65c2e291cedc8cad761e8ec64289e1c7280053fe6f1a22e866b4f
Description:
Amount (in satoshis): 500
Fee limit (in satoshis): 500
Destination: 0324ba2392e25bff76abd0b1f7e4b53b5f82aa53fddc3419b051b6c801db9e2247
Confirm payment (yes/no): yes
Got quote for 29411 asset units at 17 msat/unit from peer 038dbb70e3484da0bed806156f5270d39b480a659c82fb4b56ba3dcbe0edd74d55 with SCID 15907459453197872513
```

![image](https://github.com/user-attachments/assets/43f86e08-f2fd-46f4-8bab-b957b2774058)
