### ISSUE TITLE
tapchannel/[bug]: if asset invoice amount in satoshi exceeds channel capacity, path finding spins indefinitely

### ISSUE THREAD

**Issue by guggero** [lightninglabs/taproot-assets#1013]
When an invoice is attempted to be paid where the asset amount expressed in satoshi is larger than the actual satoshi capacity of the channel, then [this check](https://github.com/lightningnetwork/lnd/blob/1f86f38f36d965342b97ba69856b11bf815b579b/routing/unified_edges.go#L149) fails and the path finding algorithm thinks it cannot use the channel.
That leads to the path finding mechanism to try and split the amount into smaller and smaller pieces, but still failing to send the total because the sum still exceeds the capacity.

[4-test_custom_channels_large-Dave-tmp__.log](https://github.com/user-attachments/files/16181437/4-test_custom_channels_large-Dave-tmp__.log)
[3-test_custom_channels_large-Charlie-tmp__.log](https://github.com/user-attachments/files/16181439/3-test_custom_channels_large-Charlie-tmp__.log)

**Comment by dstadulis** [comment]
Related to #1060

**Comment by GeorgeTsagk** [comment]
Closed by https://github.com/lightningnetwork/lnd/pull/8908

(commit: https://github.com/lightningnetwork/lnd/pull/8908/commits/d80bca8c6ffe460dd8ec5ad0b911a0f858b5e74a)
