### ISSUE TITLE
[bug]: FundChannel UX improvements

### ISSUE THREAD

**Issue by vanditshah99** [lightninglabs/taproot-assets#1026]
We are facing weird issue with lit 
```
{
    "version": "0.13.99-alpharc4 commit=v0.13.99-alpha.rc4"
}
```

We minted two assets having genesis transactions as
```
https://mempool.space/testnet/tx/2d74f4358ab17ddbc296afe2272e3b82d1be395b0c7dddd6e43275f024aa06c3 
```
```
https://mempool.space/testnet/tx/2d74f4358ab17ddbc296afe2272e3b82d1be395b0c7dddd6e43275f024aa06c3
```

This two transaction are confirmed, but when we try to do a fund channel with peer using the following command
```
litcli -n testnet --macaroonpath /root/.lnd/data/chain/bitcoin/testnet/admin.macaroon ln fundchannel --node_key 020c3b59b1854d31b94c0dd9df1019d251b4cd5565129f7ad16e3ec8c4671afd8c --sat_per_vbyte 20 --asset_amount 500000000 --asset_id 9f697c53c52ad5b80740caf3b9e299c8491c04625b224632eb85a9633f2a1522
```

We receive this error 
```
[litcli] error funding channel: rpc error: code = Unknown desc = error funding channel: unable to fund vPacket: error fetching input proof: cannot fetch proof for input asset: unable to find proof
```

Also post this error asset list API of tapcli doesn't show the newly minted asset anymore!

[df29cf30b0e641d26120bcecd43847edc0842b4dcb6cc858a2c5f3483688954b.txt](https://github.com/user-attachments/files/16248012/df29cf30b0e641d26120bcecd43847edc0842b4dcb6cc858a2c5f3483688954b.txt)
[2d74f4358ab17ddbc296afe2272e3b82d1be395b0c7dddd6e43275f024aa06c3.txt](https://github.com/user-attachments/files/16248023/2d74f4358ab17ddbc296afe2272e3b82d1be395b0c7dddd6e43275f024aa06c3.txt)

**Comment by guggero** [comment]
Thanks for the logs. Does the node that received the channel (the one not opening it) have universe sync turned on?
I think you need the new `--taproot-assets.universe.sync-all-assets` flag and it needs to be connected to the same federation the channel creator is. Because in the logs I don't see any proof sync messages on the receiver.

**Comment by guggero** [comment]
@vanditshah99 one thing that's not fully clear to us is what steps you actually took. Are we correct in assuming that you minted the asset on the node that later opened the channel? Then waited for the transaction to confirm before attempting the channel open?

**Comment by vanditshah99** [comment]
Yes we took the following steps
1. Minted the asset
2. Finalized the batch
3. Waited for Tx to confirm
4. Fund channel using LIT
