### ISSUE TITLE
[bug]: FundChannel Ack Timeout Issue

### ISSUE THREAD

**Issue by vanditshah99** [lightninglabs/taproot-assets#1038]
We tried the following scenario

We minted an asset on Tapd Standalone Instance (T1) 
```
{
    "version": "0.4.0-alpha.rc4 commit=v0.4.0-rc4",
    "lnd_version": "0.18.1-beta",
    "network": "testnet3",
    "lnd_identity_pubkey": "02ac55f686b46ae6fc60924fe2115b1a7b64d4d71c0de2265a1ef0136d680b1c61",
    "node_alias": "SpeedDev2",
    "block_height": 2869499,
    "block_hash": "00000000000000076bad3bf7db76e38f1842c50b3b32bd104bab93b056c778c6",
    "sync_to_chain": true
}
```
And transferred few Bucks to LiT-Tapd Instance (T2)

Now from T2 we raise an fundchannel request
```
litcli -n testnet --rpcserver=localhost:8443 --macaroonpath=~/.lnd/data/chain/bitcoin/testnet/admin.macaroon ln fundchannel --node_key=02ac55f686b46ae6fc60924fe2115b1a7b64d4d71c0de2265a1ef0136d680b1c61 --asset_amount=50000000 --asset_id=f8ffc554dad8a3780c408297a70b70af1c8d96cae3c167ff55cbd6308edb2a08 --push_amt=50000
```
This fails stating
```
[litcli] error funding channel: rpc error: code = Unknown desc = error funding channel: didn't receive funding ack after 30s
```
The logs of t1 are as follows
[t1 tapd node.txt](https://github.com/user-attachments/files/16332009/t1.tapd.node.txt)
[t1 lnd node.txt](https://github.com/user-attachments/files/16332006/t1.lnd.node.txt)

The logs of T2 node are following
[t2_ack.txt](https://github.com/user-attachments/files/16331983/t2_ack.txt)

Also, when this error is encountered, we face this issue of asset not showing in asset list grpc.
```
https://mempool.space/testnet/tx/6718cd84a2a5104b5ce7e1f6765750c1a6bf3f885248a9cae4bb5a71ab239e17#vout=0

```
5 conf already at this moment

Also litcli getinfo(T2 Node)
```
{
    "version": "0.13.99-alpharc4 commit=v0.13.99-alpha.rc4"
}
```

**Comment by Roasbeef** [comment]
Working on adding a fast fail check, so we just bail out if the other nodes doesn't support the channel type sooner with a nice error message.

**Comment by Roasbeef** [comment]
This is fixed by https://github.com/lightninglabs/taproot-assets/pull/1041
