### ISSUE TITLE
[feature]: add channel conditional validation to `AddAsset*Order` RPC endpoints

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#1053]
Currently, the `AddAssetBuyOrder` and `AddAssetSellOrder` RPC endpoints initiates the RFQ communication process with a specified target peer. This issue proposes a modification to the endpoint to include a pre-condition check. Specifically, the RFQ process should only commence if there is an existing tap channel for the specified asset between the local node and the target peer, and that channel has sufficient funds. If these conditions are not met, the endpoints should return a helpful error.

**Comment by dstadulis** [comment]
RFQ rework is a prerequisite
