### ISSUE TITLE
unit-race: find workaround for sqlite data race

### ISSUE THREAD

**Issue by guggero** [lightninglabs/taproot-assets#107]
Looks like our race unit tests are affected by https://gitlab.com/cznic/sqlite/-/issues/62. We need to find a workaround for that as it doesn't seem like the problem will be fixed any time soon.

**Comment by Roasbeef** [comment]
Is this still an issue?

**Comment by guggero** [comment]
I haven't seen this happen anymore. Not sure if we did something wrong or this only happened a single time? Closing for now, can always re-open if it happens again.
