### ISSUE TITLE
[bug]: Error finding asset channel to use: multiple asset channels found for asset 

### ISSUE THREAD

**Issue by javiervargas** [lightninglabs/taproot-assets#1085]
### Background

Doing some tests opened channels for the same asset resulting in 2 channels.. one from node 1 to node 2 and second from node 2 to node 1.  Now were unable to pay invoices as we get this message about multiple channels found.  (logs below).  Invoices worked once we closed 1 channel. 

### Your environment

```sh
tapcli --tlscertpath ~/.lit/tls.cert --rpcserver=localhost:8443 --network=testnet getinfo
{
    "version": "0.4.1-alpha commit=v0.4.2-0.20240809013914-a8d8b5a46552",
    "lnd_version": "0.18.0-beta",
    "network": "testnet3",
    "lnd_identity_pubkey": "02db3ba0d5b512f58ee0833b40ea62c62e78c1d997457cc03caeb17d06ec12ab69",
    "node_alias": "02db3ba0d5b512f58ee0",
    "block_height": 2873458,
    "block_hash": "00000000000030afb7a34004ff8df80a9926e750ddbd4e245546d45c0320959d",
    "sync_to_chain": true
}

uname -mrsv                          

Linux 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64

bitcoind --version 

Bitcoin Core version v25.0.0
```

### Steps to reproduce

Create two channels for same asset.

```sh
lnclit getinfo
{
    "version":  "0.18.0-beta commit=lightning-terminal-v0.13.992-experimental",
    "commit_hash":  "f7d6d72bc6b3d97330c9ffdf62d0df14b6769508",
    "identity_pubkey":  "02db3ba0d5b512f58ee0833b40ea62c62e78c1d997457cc03caeb17d06ec12ab69",
    "alias":  "02db3ba0d5b512f58ee0",
    "color":  "#3399ff",
    "num_pending_channels":  0,
    "num_active_channels":  4,
    "num_inactive_channels":  9,
    "num_peers":  5,
    "block_height":  2873458,
    "block_hash":  "00000000000030afb7a34004ff8df80a9926e750ddbd4e245546d45c0320959d",
    "best_header_timestamp":  "1723585521",
    "synced_to_chain":  true,
    "synced_to_graph":  true,
    "testnet":  true,
    "chains":  [
        {
            "chain":  "bitcoin",
            "network":  "testnet"
        }
    ],


litcli --network=testnet --macaroonpath=~/.lnd/data/chain/bitcoin/testnet/admin.macaroon ln payinvoice lntb847n1pnthxwspp5lrsaa6z7wvxwe9lnggl4ws4x45ken6lw53qswvf47gtdf0hxgktqdqvdpjkcurxw4kqcqzzsxqzfvrzjqtdnhgx4k5f0trhqsva5p6nzcch83swejazhespu46ch6phvz24kjk8r4pcydvk7nyqqqqlgqqqqqqgq2qsp5ffcm3ksfl2jhdzfr2q3utfl3epssfszk4v7cj3ztsd6r7zc5zjts9qxpqysgqzydsm9m7l3ypy8wgh2pu2zl0dm84r3vt0kghccspjgux7c9n375py9n26e73sferna22568p7y54j3qsc7ld98rxhja9tc6ualr3qagpzzem22 --asset_id 1d39aaf567b6e68a563072c7ef3ddacea1fb178acece249851e3dc0f53c53ae3 --last_hop 037631c146daa9894527447ef9d5edc99c8b3794b5234d825d11101c998064be86 --outgoing_chan_id 3159371895731519488
Payment hash: f8e1dee85e730cec97f3423f5742a6ad2d99ebeea441073135f216d4bee64596
Description: helpful
Amount (in satoshis): 84
Fee limit (in satoshis): 84
Destination: 037631c146daa9894527447ef9d5edc99c8b3794b5234d825d11101c998064be86
Confirm payment (yes/no): yes
[litcli] rpc error: code = Unknown desc = error finding asset channel to use: multiple asset channels found for asset 1d39aaf567b6e68a563072c7ef3ddacea1fb178acece249851e3dc0f53c53ae3, please specify the peer pubkey
```

**Comment by Roasbeef** [comment]
> litcli] rpc error: code = Unknown desc = error finding asset channel to use: multiple asset channels found for asset 1d39aaf567b6e68a563072c7ef3ddacea1fb178acece249851e3dc0f53c53ae3, please specify the peer pubkey

Have you tried specifying the peer public key? 

https://github.com/lightninglabs/taproot-assets/blob/4ec0dd40a98855e5708f87cd8bfde697af7512ad/taprpc/tapchannelrpc/tapchannel.proto#L111-L114

**Comment by guggero** [comment]
@javiervargas oops, it looks like I forgot to actually add the new `--rfq_peer_pubkey` command line flag... Will create a fix right a way.

**Comment by guggero** [comment]
Will be fixed by https://github.com/lightninglabs/lightning-terminal/pull/817.

We're also going to build nightly images from the `0-19-staging` branch (which is where the `v0.13.99x-experimental` tags are being created on) with https://github.com/lightninglabs/lightning-terminal/pull/813, so hopefully by tomorrow you should have a version that fixes this in this Docker Hub repo: https://hub.docker.com/r/lightninglabs/lightning-terminal-nightly

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/lightning-terminal/pull/817. Nightly build with changes should be available at https://hub.docker.com/r/lightninglabs/lightning-terminal-nightly in a couple of hours or so.
