### ISSUE TITLE
[Routing Saga]: Limit route contstruction and invoice clearing over payment channel settlement

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#1102]
The tapd daemon's logic for constructiong routes and clearing HTLC state needs to be tailored tighter to expectations when generating invoices. This lack of specificity leads to several issues related to how the daemon views payment bandwidth and settles HTLCs.

**Related Issues:**

- [x] https://github.com/lightninglabs/taproot-assets/issues/1008
- [x] https://github.com/lightninglabs/taproot-assets/issues/1060
* [Continue to add other issues]

**Solution:**

A more robust solution is needed to ensure the tapd daemon can handle HTLCS for invoices with custom data. This may involve changes to how the daemon selects and clears payment-channel state, as well as how it settles HTLCS.

**Comment by dstadulis** [comment]
Assigned to George since https://github.com/lightninglabs/taproot-assets/issues/1008 is remaining task

**Comment by GeorgeTsagk** [comment]
Since both PRs are now merged I'm closing this
