### ISSUE TITLE
[bug]: Validate transaction's fee for min-relay suitability before broadcast

### ISSUE THREAD

**Issue by HannahMR** [lightninglabs/taproot-assets#1105]
### Background

[Maintainer edit: Transactions' fees may be created which are insufficient to meet the backend's stipulated minimum relay amount]
If an asset channel is opened without specifying the sats per vbyte amount, a too low fee may be used. The channel then gets stuck as pending and another channel can't be opened as there is already a pending channel for that asset. 

### My environment

I believe I was running litd v0.13.99 in integrated mode on a Ubuntu server at the time this error occurred. 

### Steps to reproduce

Open an asset channel using the standard litcli command while not specifying the sats per vbyte amount. 

Command used to open channel:

    $ litcli --network=testnet --tlscertpath ~/.lit/tls.cert --macaroonpath=~/.lnd/data/chain/bitcoin/testnet/admin.macaroon ln fundchannel --node_key [peer node pub key]  --asset_amount [amount] --asset_id [id of asset to be included in the channel]

### Expected behavior

An appropriate fee is used for the tx, the tx is confirmed and the channel is opened. 

### Actual behavior

The fee is insufficient and the channel is not broadcast and stays in a pending state preventing the opening of another channel using that asset. 

Error received: 

    [litcli] error funding channel: rpc error: code = Unknown desc = error funding channel: error requesting delivery: unable to broadcast transaction f1f72cf96a37b677798392824744112da8f09015f6fc89dfe6de335cdf8a3a0e: rpc error: code = Unknown desc = undefined: min relay fee not met

Appearing in the logs:

    2024-07-17  17:57:57.885  [ERR] BTCN: Broadcast attempt failed: undefined: -26: min relay fee not met, 254 < 255

**Comment by dstadulis** [comment]
Thanks!  Will tweak the issue a bit

**Comment by jharveyb** [comment]
AFAICT we're funding the TX without sanity checking the resulting feerate in `tapd` before we sign the TX and pass it to LND. I think we actually have a similar issue elsewhere, where we fund without immediately checking the resulting TX against some floor feerate. We could probably just add that check to `WalletAnchor`.

Funding for channel open:

https://github.com/lightninglabs/taproot-assets/blob/72b93f84a0afa08e01c99d582357672133fc9b20/tapchannel/aux_funding_controller.go#L1063

A heavyweight check of TX validity:

https://github.com/btcsuite/btcd/blob/2b53ed198955ac40fe5b3ce4a854e9f5bfa68258/mempool/mempool.go#L1315

I think most of those checks are not needed so we could use only the feerate check if it was exported:

https://github.com/btcsuite/btcd/blob/2b53ed198955ac40fe5b3ce4a854e9f5bfa68258/mempool/mempool.go#L1681

Specifically, the top half of this function. I thought we already had something similar but I think it was for simplifying the calculation of feerate for a funded TX.

I also don't see this method exposed, which would be useful:

https://github.com/lightningnetwork/lnd/blob/e8c5e7d5ce4b79117ef9ab497745fea3a1bffb36/lnwallet/chainfee/estimator.go#L81

If we're going to skip the fee estimator.

**Comment by dstadulis** [comment]
Current focus:
Solution proposed, guggero approved design
  - Requires: Impl in lndclient
    - Requires lnd bumped to 18.3
