### ISSUE TITLE
[feature]: Support `lnd` hold/hodl invoice API for Taproot Asset channels

### ISSUE THREAD

**Issue by lukegao209** [lightninglabs/taproot-assets#1133]
Is there any plan to add support for Taproot assets in the /v2/invoices/hodl API of LND?

**Comment by Roasbeef** [comment]
Yes. Although I think it's already possible today, but the API isn't hooked up fully.

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/taproot-assets/pull/1184.
