### ISSUE TITLE
[bug]: REST FundChannel Method Incorrectly Implemented as GET Instead of POST and Does Not Work

### ISSUE THREAD

**Issue by V0nMis3s** [lightninglabs/taproot-assets#1219]
### Background

The `FundChannel` method in the REST API is currently implemented as a `GET` method, but this is semantically incorrect as it performs a state-changing operation (funding a channel). Moreover, the `GET` implementation fails to function even when used as intended, returning a malformed public key error.

This issue renders the method unusable and violates RESTful principles. The method should be implemented as a `POST` and accept the `FundChannelRequest` object in the body of the request.

### Your environment

```sh
tapcli getinfo
# tapd version: 0.4.1-alpha commit=v0.4.2-0.20240815180811-2110839696cb
# lnd version: 0.18.0-beta
# network: regtest

uname -mrsv
# inux 6.8.0-49-generic #49-Ubuntu SMP x86_64

bitcoind --version
# Bitcoin Core version v27.0

```

### Steps to reproduce

1. Start in [integrated mode](https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/integrating-litd), and ensure it is running.
2. Attempt to fund a channel using a GET request with query parameters:
```sh
curl -k -X GET \
  https://{host}:{port}/v1/taproot-assets/channels/fund \
  -H "Grpc-Metadata-macaroon: $(xxd -ps -c 10000 /path/to/admin.macaroon)" \
  -H "Content-Type: application/json" \
  --data-urlencode "asset_amount=100" \
  --data-urlencode "peer_pubkey=base64_pubkey" \
  --data-urlencode "asset_id=base64_asset_id="
```
3. Observe the response:
```json
{
  "code": 2,
  "message": "error parsing peer pubkey: malformed public key: invalid length: 0",
  "details": []
}
```
4. Attempt the same operation as a POST request with the request body:
 ```sh
curl -k -X POST \
  https://{host}:{port}/v1/taproot-assets/channels/fund \
  -H "Grpc-Metadata-macaroon: $(xxd -ps -c 10000 /path/to/admin.macaroon)" \
  -H "Content-Type: application/json" \
  -d '{
        "asset_amount": "100",
        "peer_pubkey": "base64_pubkey",
        "asset_id": "base64_asset_id="
      }'
```
5.Observe the response:
```json
{
  "code": 12,
  "message": "Method Not Allowed",
  "details": []
}
``` 

### Expected behavior

The `FundChannel` method should:
- Be implemented as a `POST` REST method.
- Accept the FundChannelRequest object in the request body.
- Successfully process the request and return a valid response.

### Actual behavior

The current implementation:
- Uses the `GET` method, which is semantically incorrect for a state-changing operation.
- Fails to parse query parameters correctly, resulting in an error: "error parsing peer pubkey: malformed public key: invalid length: 0".
- Does not work when attempted as a `POST`, returning "Method Not Allowed".

### Possible Cause of the Issue
**Default Behavior of grpc-gateway:**
The gRPC-Gateway plugin maps RPC methods to HTTP methods (`GET`, `POST`, etc.) based on the request message's fields when no explicit `google.api.http` annotation is provided in the `.proto` file. In this case, the `FundChannelRequest` message contains scalar fields (e.g., `uint64`, `bytes`), which can be represented as query parameters. As a result, gRPC-Gateway defaults to mapping this RPC method to `GET`.

**Comment by GeorgeTsagk** [comment]
Hey @V0nMis3s , thanks for flagging this, created a [PR](https://github.com/lightninglabs/taproot-assets/pull/1220) that converts the endpoint to POST
