### ISSUE TITLE
[bug]: Terminal crashes

### ISSUE THREAD

**Issue by lukegao209** [lightninglabs/taproot-assets#1227]
### Background
Version ： lightninglabs/lightning-terminal:v0.14.0-alpha.rc1-path-prefix

When the RFQ accesses the Price Oracle, if it returns an error indicating that the asset is not found, the terminal crashes.

**Comment by ffranr** [comment]
This should probably be moved to the terminal repo.

@lukegao209 do you have any logs just in case tapd is the cause of the crash?

**Comment by lukegao209** [comment]
You can add our Price Oracle server and call addinvoice with an assetId that does not exist on the Price Oracle. This will cause the terminal to crash.

--taproot-assets.experimental.rfq.priceoracleaddress=rfqrpc://oracle.ln.exchange:443

**Comment by guggero** [comment]
Thanks. But if you have access to the stack trace of the crash, that would help us to fix the bug even quicker.

**Comment by lukegao209** [comment]
> Thanks. But if you have access to the stack trace of the crash, that would help us to fix the bug even quicker.
here is the crash logs : 
2024-12-03 01:03:01.202 [INF] LITD: Handling gRPC request: /litrpc.Proxy/BakeSuperMacaroon
2024-12-03 01:03:01.216 [INF] LITD: Handling gRPC request: /tapchannelrpc.TaprootAssetChannels/AddInvoice
2024-12-03 01:03:01.790 [WRN] RFQS: failed to query bid price from price oracle for outgoing buy request: failed to query price oracle for bid price: OracleError(code=0, msg=unsupported subject asset)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1672b80]

goroutine 26389 [running]:
github.com/lightninglabs/taproot-assets/rfq.(*Negotiator).HandleOutgoingBuyOrder.func1()
        github.com/lightninglabs/taproot-assets@v0.5.0-rc1/rfq/negotiator.go:197 +0x370
created by github.com/lightninglabs/taproot-assets/rfq.(*Negotiator).HandleOutgoingBuyOrder in goroutine 26378
        github.com/lightninglabs/taproot-assets@v0.5.0-rc1/rfq/negotiator.go:158 +0xd8

**Comment by guggero** [comment]
Great, thank you! Will create a fix today.

Just a heads up though (and yes, I know this wasn't in the release notes yet, will add today): The oracle RPC has had some breaking changes. So the implementation of the software running at `oracle.ln.exchange:443` will need to be updated for `litd v0.14.0-alpha.rc1`.
See the [example code](https://github.com/lightninglabs/taproot-assets/blob/main/docs/examples/basic-price-oracle/main.go), the [RPC definition](https://github.com/lightninglabs/taproot-assets/blob/main/taprpc/priceoraclerpc/price_oracle.proto) and the general description of how the new [fixed point math and price quotes](https://github.com/lightninglabs/taproot-assets/blob/main/docs/rfq-and-decimal-display.md) work.

But of course things shouldn't crash if not updated, so we'll definitely fix that.

**Comment by lukegao209** [comment]
thanks . our price oracle(oracle.ln.exchange:443) has been upgraded to v5.0 already.
