### ISSUE TITLE
Link level bidirectional strict-forwarding

### ISSUE THREAD

**Issue by GeorgeTsagk** [lightninglabs/taproot-assets#1247]
## Description

A node that creates an `invoice` with the intention of receiving asset type X will want to settle `invoice` only if the HTLCs paying to it carry units of asset type X.

In our last iteration we added a guard to the `AuxInvoiceManager` which prohibits asset invoices being settled by HTLCs carrying pure btc (see [related PR](https://github.com/lightninglabs/taproot-assets/pull/1144), and [specific code section](https://github.com/lightninglabs/taproot-assets/blob/main/tapchannel/aux_invoice_manager.go#L153-L168))

## Problem

While this is partially effective, we still have a few open vectors:
- A btc invoice may still be paid for with HTLCs carrying assets
- An asset invoice may not be settled by btc HTLCs, but it may be settled by HTLCs carrying assets of a different type

## Proposed Solution

- [x] Add a guard against the 2nd direction violation (btc invoice <- asset HTLCs) (closed by #1244)
- [ ] #1255

**Comment by dstadulis** [comment]
Closing as strict forwarding was delivered which was necessary for v0.5
