### ISSUE TITLE
rpc+proof: create analogue of Bitcoin's "signmessage" call for generic taro assets

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#160]
We should add a way for asset owners to prove to third parties that the assets exist and also they control the keys to sign over them. We can split this into two components: 
  1. Revealing the necessary set of inclusion proofs (already have all the utilities for this from the proof file) 
  2. Generating a valid looking, but protocol-invalid state transition 

Thinking about it a bit, what we want is a serialized version of `proof.Proof` (which maybe we rename to `StateTransition`), but it uses an incorrect prev ID (a special one for this purpose) to generate the Taro level witness data. With that, we can re-use just about everything, and all we need to think about is the format we want to serialize ownership proofs like this.

**Comment by jharveyb** [comment]
Fixed in https://github.com/lightninglabs/taproot-assets/releases/tag/v0.2.0
