### ISSUE TITLE
bip-taro: implement interactive transfers for collectibles 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#21]
[Defined in this section](https://github.com/Roasbeef/bips/blob/bip-taro/bip-taro.mediawiki#collectible-asset-transfers), collectible transfers are a bit easier, since they don't require the transmission of the extra split commitment proofs and non-inclusion proofs. Along the way, we'll want to record the concrete items that need to be sent back and forth in order to finalize the PSBT flow. 

A good way to implement this flow is likely as a state machine that's oriented around the types/messages it'll send/recv between the sender and receiver. This way the logic is generic and can be used as libraries elsewhere, and also will help us to better specify what's needed from a sender and receiver, and also zoom in on exactly what needs to be sent between the two parties.

**Comment by jharveyb** [comment]
Fixed in https://github.com/lightninglabs/taproot-assets/releases/tag/v0.2.0
