### ISSUE TITLE
BIP updates

### ISSUE THREAD

**Issue by jharveyb** [lightninglabs/taproot-assets#210]
Need to make multiple Taro BIP updates to reflect spec changes made during implementation.

Non-interactive transfers ( from #159 , #172 , #176 ) :
- [ ]  Unconditional use of split commitments for non-interactive transfers
- [ ] Zero-value root locators for full-value sends
- [ ] NUMs key use for full-value sends
- [ ] Restricted support for collectibles in split commitments
- [ ] SplitCommitment clearing when computing input PkScripts for assets received non-interactively

Key encoding and storage ( from #187 )
- [x] Handle all keys in addresses, assets, and records as compressed instead of x-only

Asset family to asset group rename ( from #200 )
- [x] Rename asset family to asset group

**Comment by guggero** [comment]
Tracking remaining items here: https://github.com/lightninglabs/taproot-assets/issues/293
