### ISSUE TITLE
rpc getinfo

### ISSUE THREAD

**Issue by amovfx** [lightninglabs/taproot-assets#218]
Hey guys,
I think taro could benefit from a getinfo rpc call. This is inline with other daemons like bitcoin and lnd. I've found need of it in my attempt in integrating taro into polar where a getinfo call is used to check if a daemon is running.

Chatting with Jonathan Harvey-Buschel, he suggested posting up an issue to get feedback and  version, LND version if we can get it, network, # of assets, # of UTXOs to start?

I have the skeleton done, and can add whatever parameters we deem necessary. Anybody have other suggestions?

**Comment by Roasbeef** [comment]
Thanks for starting this, we've merged this into the main branch.
