### ISSUE TITLE
Support multi-asset groups during the minting process

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#233]
## Background
Very very broadly, an `asset group` should be considered to be the set of assets which share some sort of common, identifying property across discrete, more unique instances of the asset (e.g. shares in a company vs a share of the company but with voting rights etc).  How the taro daemon handles this interchangeability currently depends on the minting process.

After #214 is merged, the minting process is excessively constrained to not allow for two asset groups to be minted during the original mint (a deficient property)

## Deliverables
This issue shall be satisfied by a PR which allows for multi-asset groups to be created during the minting process.  i.e. the daemon supporting minting say a regular share and a preferred share during the same, initial minting

Asset groups 
-  Must have an identical 
   - group key
-  may have different 
   - metadata or data of the asset may be varied across assets (e.g. the distinguishing properties)

### Code changes:
- [ ] New CLI flags
   - [ ] Shall specify which group an asset would be minted into. Which would need to (tentatively include)
     - [ ] Enable emission
     - [ ] Group number
- [ ] Inside the minter logic:
    - [ ] Need new field on seedlings
      - Which maps to this previous CLI argument (group number)
        - So that, tarod can associate the seedlings to the same group
- [ ] Modify DB to persist multi-asset-groups-minting data to persistence data if tarod restarts during the minting process; so that state isn’t lost.
- [ ] Investigate proto or RPC changes which would need to be made
- [ ] Caretaker changes:
  - [ ] Check these CLI flags to make group keys to match them.
  - [ ] Add necessary extra logic

## Notes
The issue's changes merely need to be persisted during minting but after minting, no data persistence needed,
Asset definitions wont need to change, besides during minting.

**Comment by jharveyb** [comment]
From offline discussion:

Instead of adding assets into the new group individually, add the multi-asset group atomically with one RPC call. This avoids multiple issues (what if the batch ticker fires while I'm adding assets to my group?), and simplifies the RPC changes (no need to expose tagging of assets to map them to tentative groups).

**Comment by jharveyb** [comment]
From further offline discussion:

A better path to enable this feature may be to make the planter more flexible overall, specifically:

- Batch cancellation or pausing #251 
- Batch finalizing without adding a seedling #252 
- Change the minting ticker to be off by default, so all batches must be finalized manually
- Add a new RPC call to display the state of the minter / the pending batch
- Support multiple minting batches, so groups do not have to be constructed all at once
- Support specifying a batch for minting RPC calls, to allow for more complex batch construction

For cancelling a batch, adding a new 'cancelled' state may be preferable to deletion from the DB, to make accounting or auditing of minting activity easier. It may also be useful for external programs to have more flexibility in how they construct batches.

For multiple batches, the default behavior could be that all batches must be finalized manually. If only one batch exists, specifying the batch for an action is optional. If multiple batches exist, then a batch must be specified to perform any further actions. Eventually we can re-enable the ticker, which would only cause a batch finalization if there is only one pending batch.

**Comment by jharveyb** [comment]
Fixed in https://github.com/lightninglabs/taproot-assets/releases/tag/v0.2.0
