### ISSUE TITLE
Add proto-level enum to messages generated by Event Streamer

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#239]
MVP functionality of event notifications were added to tarod with #235. Eventually we will want to include more information in the messages generated by the Event Streamer functionality to enhance the functionality of the RPC and how it can be used.  This issue shall be satisfied by a PR which adds proto-level enums to the messages that various tarod events which are proccessed by the Event Streamer RPC.

Once #222 #217 are merged, a more practical appreciation for the event notifications will be known and can influence the design choices.

**Comment by ffranr** [comment]
@dstadulis I think this issue is complete. We use enums for notification events.
