### ISSUE TITLE
Support for internal splits / self-spends

### ISSUE THREAD

**Issue by jharveyb** [lightninglabs/taproot-assets#240]
An internal split is defined as using a split commitment to 'split' one asset leaf into multiple, which may be useful for leaf management or just general testing.

We've already seen bug reports related to this use case, as the send state machine and proof import logic assumes that the transfer receiver is a separate `tarod` instance.

Existing reports:

https://github.com/lightninglabs/taro/issues/234

Panic caused by DB query reutnring an empty array instead of an error, direct access since we assume an asset transfer row is already present

https://github.com/lightninglabs/taro/issues/237

DB lock contention (SQLITE_BUSY) when `tarod` tries to both send and receive proofs via mailboxes

**Comment by habibitcoin** [comment]
ACK

would be super helpful

**Comment by Roasbeef** [comment]
Working on reproducing this.

**Comment by jharveyb** [comment]
Fixed in https://github.com/lightninglabs/taproot-assets/releases/tag/v0.2.0
