### ISSUE TITLE
Recommence processing asset send from optimal state

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#257]
The asset send state machine passes around a struct called  `sendPackage`. The `SendState` field of `sendPackage` is the next state of the state machine to execute.

Currently, at restart, the `SendState` field is not populated. It's value is not persisted to disk.

The work necessary to complete this issue: `SendState` field should be persisted and recovered from disk such that `sendPackage` processing recommences from an optimal state.

**Comment by Roasbeef** [comment]
I think we need to shape this up a bit: are we targeting fixing some fault tolerance holes in sending?

**Comment by ffranr** [comment]
I think we should close this issue. A lot has changed since I created it. It doesn't solve a particular problem. And it isn't obvious to me right now that it would make the sending process more robust. I think at best it might make troubleshooting easier. But even then the logs should contain the same information.
