### ISSUE TITLE
asset wallet: introduce coin locking and coin selection mutex

### ISSUE THREAD

**Issue by guggero** [lightninglabs/taproot-assets#261]
The asset wallet introduced in https://github.com/lightninglabs/taro/pull/244 does not allow a coin to be marked as being used (=locking), which needs to be done at the database layer.
Once we can mark asset coins as being used/locked, we also need to make sure that access to coin selection and the locking APIs are covered by a single coin selection mutex similar to how it's done in `lnd`.

**Comment by Roasbeef** [comment]
May also want to have a bit that says if an output has been fully spent or not. Either that, or we need to delete it.

**Comment by dstadulis** [comment]
related issue #374
