### ISSUE TITLE
Create `list batches` funcitonality to enumerate asset-update batches

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#272]
This tracking issue will be fulfilled by a small PR to create `list batches` funcitonality to enumerate asset-update batches within Taro.  Purpose of the small PR is to get the feature into `main` quickly for it to be built on for other feature branches (avoiding rebase churn)

**Comment by jharveyb** [comment]
Fixed with https://github.com/lightninglabs/taproot-assets/releases/tag/v0.2.0
