### ISSUE TITLE
Multi input spend methods are feature incomplete for multi assetIDs with same group

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#299]
### Current state

I believe that this is the current state:

In an interactive spend (vPSBTs) we can spend multiple different asset IDs and from different asset group.

And non-interactively (spend via address/invoice) we can spend multiple coins of a single asset ID.

### Missing features

When spending non-interactive, we should be able to spend multiple different coins of multiple different asset IDs from a single asset group. That work is blocked on issue https://github.com/lightninglabs/taproot-assets/issues/291 . Depending on how that issue is resolved we might also be able to spend multiple different asset groups non-interactively (with a single address).

---

Is the above accurate @guggero @jharveyb @GeorgeTsagk @dstadulis  ?

**Comment by dstadulis** [comment]
related to #291

**Comment by ffranr** [comment]
We really need to finish https://github.com/lightninglabs/taproot-assets/issues/291 first before we can start this issue.

**Comment by Roasbeef** [comment]
Re the final point, seems like the abstractions support it, but it's a matter of the mental model a dev has in mind once they start to create interactions like this.

**Comment by ffranr** [comment]
cc @dstadulis I've simplified this issue in an attempt to clarify the current state and what features we might need to add.

I think we can close this issue as it isn't really serving a purpose right now.
