### ISSUE TITLE
Extend getinfo RPC responses to include more comprehensive `tapd` information

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#311]
#220 created the getinfo RPC.  Extending this command with other useful information like

- information about the lnd node `tapd` is paired with
- Universe connection status
- chain state / syncing
- [your idea here]

Please add comments to the issue for additional fields your use case would benefit from, with a short motivation description.

**Comment by natalypeyioti** [comment]
I have started working on this issue and I would appreciate some clarification on the additional fields requested for this command. I want to ensure that I fully understand the requirements.

1. Information about the lnd node `tapd` is paired with: Could you please provide more details on what specifically should be included in this information? Would including the public key and active channels of the paired node be sufficient, or are there other specific details that should be considered?

2. Universe connection status: Can you please elaborate on what is meant by "Universe connection status"?

3. Chain state / syncing: For this field, should I provide details about the current block height or any other specific information related to the synchronization process of the blockchain? It would be helpful to understand the exact information that would be valuable in this context.

**Comment by positiveblue** [comment]
Hello Nata, 

for 1) I would expect to have things like: node alias, address, lnd version, block_height/block_hash, and if it is synced_to_chain

for 2) What I would do is to check the [cli commands](https://github.com/lightninglabs/taproot-assets/blob/main/cmd/tapcli/universe.go#L43) for universes and check what is useful. For example the list of hosts your are connected and maybe [some high levels stats](https://github.com/lightninglabs/taproot-assets/blob/main/rpcserver.go#L2845)

For 3) you can check what lnd provides but `block_height`, `block_hash` and  `synced_to_chain` sound like a good starting point.

We can always iterate on this so improving what we already have is already a success here :rocket:

**Comment by jharveyb** [comment]
Resolved in v0.3.
