### ISSUE TITLE
Ensure daemon is robust to chain re-orgs

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#317]
_unfinished_

**Comment by guggero** [comment]
I did a quick investigation in how the `lnd` RPCs behave on a re-org.
Adding some additional debug statements and RPC calls to the `open_channel_reorg_test` itest:

```
=== RUN   TestLightningNetworkDaemon/tranche00/64-of-132/btcd/open_channel_reorg_test
    lnd_open_channel_test.go:90: Funding txid: b5e0bb6db4657d9ede47c4fb6550ad240ccbd66a2b865f53936a01e0bbf7d813
    lnd_open_channel_test.go:113: Got transaction event, tx_hash=b5e0bb6db4657d9ede47c4fb6550ad240ccbd66a2b865f53936a01e0bbf7d813, block_hash=5d98ef3a15a6b92a455e899461789927b3cb1a35a435324eacbc6401b8bdee9d, confirmations=1
    lnd_open_channel_test.go:143: Got confirmation event for tx_hash=b5e0bb6db4657d9ede47c4fb6550ad240ccbd66a2b865f53936a01e0bbf7d813, block_hash=5d98ef3a15a6b92a455e899461789927b3cb1a35a435324eacbc6401b8bdee9d

(actual reorg happens)

    lnd_open_channel_test.go:145: Got reorg event for tx_hash=b5e0bb6db4657d9ede47c4fb6550ad240ccbd66a2b865f53936a01e0bbf7d813
    lnd_open_channel_test.go:113: Got transaction event, tx_hash=b5e0bb6db4657d9ede47c4fb6550ad240ccbd66a2b865f53936a01e0bbf7d813, block_hash=3e903b6f24bedf8329941375f9510024b5ecf8391fcf1367159e4c42e45b9163, confirmations=1
    lnd_open_channel_test.go:143: Got confirmation event for tx_hash=b5e0bb6db4657d9ede47c4fb6550ad240ccbd66a2b865f53936a01e0bbf7d813, block_hash=3e903b6f24bedf8329941375f9510024b5ecf8391fcf1367159e4c42e45b9163

```

 - `transaction event` is from `lnrpc.SubscribeTransactions()` (doesn't need any input params)
 - `confirmation event` or `reorg event` is from `chainrpc.RegisterConfirmationsNtfn()` (needs TXID and output pkScript as input params)

**Comment by ffranr** [comment]
Having discussed on our call, I'm going to add functionality to simulate a re-org in our integration test. Oli mentioned that LND might have code for that already, so I'll take a look there.

**Comment by guggero** [comment]
Discussed the following two possible solutions:
1. Best UX but most amount of work: Accept 1 conf for mints/sends/receives
   1. Mark a TX as confirmed after receiving 1 confirmation, to allow the user to continue.
   2. Watch the TX using the `RegisterConfirmationsNtfn()` for potential re-orgs. If a re-org happens, update the block related parts of the proof and send the proofs to the receiver/universe again
   3. After a TX has received a safe (configurable but maybe something around 3 to 6 blocks) number of confirmations, stop watching for notifications.
2. Bad UX but very quick fix: Simply wait for a safe number of confirmations (configurable but maybe something around 3 blocks) before creating the final proofs.

The pros/cons mostly revolve around the time a user has to wait before being able to continue (e.g. the time between minting and sending an asset) and the amount of work we want to put in.

We're leaning toward option 1 but won't start working on it unless confirmed by @Roasbeef.
