### ISSUE TITLE
tapd/universe: fix potential concurrency issues related to concurrent SMT tree insertion 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#333]
Related to https://github.com/lightninglabs/taproot-assets/issues/320 and https://github.com/lightninglabs/taproot-assets/issues/324

Since going testnet production, we've seen some issues with the default Universe server related to concurrent operations causing read/write hazards/anomalies. 

We've seen instances on the prod server for certain assets where all the leaves are in place, but the universe _root_ is actually incorrect. Here's an example:
  * Leaves: https://testnet.universe.lightning.finance/v1/taproot-assets/universe/leaves/asset-id/83f3564d453ca736368fb71a6989ae8bc547d5dbac5a9d3e4f983fe43040dc29
  * Root: https://testnet.universe.lightning.finance/v1/taproot-assets/universe/roots/asset-id/83f3564d453ca736368fb71a6989ae8bc547d5dbac5a9d3e4f983fe43040dc29

In this example we have ~100 leaves, but the root commits to 11, as if there were only 11 collectibles. This then results in an invalid proof being sent out, as the root doesn't match the leaf when inserted into the tree. We _do_ always read the root from disk in order to generate an inclusion proof, but if the proof is invalid, then this will be as well. 

We have a few options here:
  * Create a system for fine grained tree locking to ensure concurrent safe MS-SMT access. 
  * Use PG advisory/table locking to lock all relevant tables for these operations. 
  * Add internal consistnecy checks to ensure the server never serves incorrect data. 
  * Update the default postgres concurrency settings. 

I think the last one may be the best options, we we've seen this elsewhere when we want to do things like log the set of universe events. AFAICT, the default is actually read uncommitted, which can introduce a lot of issues: https://github.com/jackc/pgx/blob/c7733fe52efc445f13fe9dd3e1b829587400dfb2/stdlib/sql.go#L376-L389

**Comment by Roasbeef** [comment]
Related issue in pgx: https://github.com/jackc/pgx/issues/1040

**Comment by Roasbeef** [comment]
Another option is to just slap a read/write mutex on it for now as well.

**Comment by dstadulis** [comment]
Subissue idea

itest to assert sql and postgres methods match

**Comment by Roasbeef** [comment]
Was fixed by #334
