### ISSUE TITLE
tapgarden+universe: DB issues with universe updates after minting or universe sync

### ISSUE THREAD

**Issue by jharveyb** [lightninglabs/taproot-assets#361]
May be due to a bad tapd state from previous incomplete mints, but I think it's an issue with parallel writers when building a universe tree?

```bash
2023-06-14 13:56:42.337 [WRN] UNIV: unable to sync universe state: unable to register issuance proof: unable to register new issuance: database is locked (5) (SQLITE_BUSY)
```

```bash
2023-06-14 13:33:07.077 [WRN] UNIV: unable to sync with universe server: unable to register issuance proof: unable to register new issuance: sql unique constraint violation: constraint failed: UNIQUE constraint failed: universe_leaves.minting_point, universe_leaves.script_key_bytes (2067)
```

AFAICT the universe state does stil sync correctly? Re-tested this on a fresh testnet node.

**Comment by Roasbeef** [comment]
First looks like a sqlite specific error. How many parallel writers are in that instance? There's a param we set to modify how long we should wait before returning that error. Perhaps we should also generalize our postgres serialization error handling to that as well. 

The second one just looks like something attempting to push the same proof twice. Perhaps a loop scoping bug, or some issue in the script itself?

**Comment by jharveyb** [comment]
Related, looks like assets are registered in the local Universe successfully, but error when pushing up to the federation universe:

```bash
2023-06-14 14:17:32.754 [ERR] UNIV: unable to push proof to federation: rpc error: code = Unknown desc = unable to register new issuance: db tx retries exceeded
```

We see an incomplete tree on the server side:

https://testnet.universe.lightning.finance/v1/taproot-assets/universe/roots/group-key/7b231f452afd0bfc0440f5afac5194bde858bca6388539e0d77a28afc6ebb6fe

**Comment by jharveyb** [comment]
> First looks like a sqlite specific error. How many parallel writers are in that instance? There's a param we set to modify how long we should wait before returning that error. Perhaps we should also generalize our postgres serialization error handling to that as well.

IIRC we write leaves in parallel goroutines, so 100? Probably similar issue in the second case.

**Comment by jharveyb** [comment]
After offline discussion, I think both of these share a root cause of too many parallel writers for the SQLite backend + missing retry logic + possibly low timeout.

-

We have retry logic for failed DB TXs but it is not triggered for SQLite at all right now.

Retry logic:

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/tapdb/interfaces.go#L188

Error wrapping, where `SQLITE_BUSY (5)` needs to be added as `ErrSerializationError`:

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/tapdb/sqlerrors.go#L44

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/tapdb/sqlerrors.go#L65

Concrete SQLite error:

https://gitlab.com/cznic/sqlite/-/blob/master/internal/mptest/main_darwin_amd64.go#L388

- 

We have a tapdb DB timeout of 10 seconds, and per-backend timeouts that are both 5 seconds. I'm not sure if the SQLite one should change, but it's here:

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/tapdb/sqlite.go#L76

-

An alternate mitigation would be to batch per-element writes into one large write.

This is the failing DB write in the minter, that tries to register the asset issuance proof for each asset minted:

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/tapgarden/caretaker.go#L948

The actual DB write could be taken out of this loop, where we create new slices of universe IDs, baseKeys, and mintingLeaves, and pass those to a version of RegisterIssuance that accepts slices.

During universe sync, we try to write issuance proofs fetched from the remote universe, for the same universe root, to the DB in parallel as well. This could be serialized by moving the DB writing out of the `ParSlice` block, and sending proof data out of that block via channel, and collecting for a batched write afterwards.

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/universe/syncer.go#L189

We have a similar situation with pushing proofs to the unverse, where each push is per-asset (and also parallel) vs batched:

https://github.com/lightninglabs/taproot-assets/blob/e74932ba9182a773f68252fe6a0f4b34144443c9/universe/auto_syncer.go#L330
