### ISSUE TITLE
[enhancement]: Add information-retreival caching for tapd gRPC responses

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#391]
### Background
---
An option in implementing https://github.com/lightninglabs/taproot-assets/issues/367 gRPC responses, is to add optimizations to the retrieval calls such that previous requests are cached and don't incur CPU/disk resource consumption.  Such a caching design will ensure that the total number of users that a universe can serve is higher than without the cache implemented.  

MVP functionality of universe stats doesn't require cache and as of 2023-07 this issue serves as archive to eventually address the need.

Related Information:
Caching was added to Pool's backend in
>order: implement public order cache 
f472cb1b66b5486800ca4dbbc57ecf93cdb3054c

@levmi notes that:
>[Within Terminal] caching mechanisms exist [...] with the ability to store [...] data in indexedDB

@jamaljsr can provide additional context on necessity of the feature or implementation complexity / design

### Deliverables
---
A cache which stores previous gRPC responses whose update criteria could be:
- updated per a time period
- updated per daemon events (e.g. new asset was registered with a universe, inducing the cache to update it's records)
- [As-et unspecified criteria]

### Alternatives considered
---
Refrain from implementing until more engineering bandwidth is available or universe resource consumption reaches a critical threshold, jeopardizing operational functionality.

**Comment by Roasbeef** [comment]
We have caching now.
