### ISSUE TITLE
Add versioning to proof file

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#392]
https://github.com/lightninglabs/taproot-assets/blob/7a5d5cae25f980c0ead87c0578584eafee689624/proof/proof.go#L80

https://github.com/lightninglabs/taproot-assets/blob/7a5d5cae25f980c0ead87c0578584eafee689624/proof/file.go#L50C2-L51

### Deliverables

encode version within
- [ ] proof
- [ ] actual transition data

**Comment by guggero** [comment]
This was fixed by https://github.com/lightninglabs/taproot-assets/pull/381 (on the `v0-3-0-staging` branch) and is updated in the BIP with this PR: https://github.com/Roasbeef/bips/pull/40
