### ISSUE TITLE
[bug]: /taprpc.TaprootAssets/FetchAssetMeta unknown permission required for method

### ISSUE THREAD

**Issue by sidahmedabdelillah** [lightninglabs/taproot-assets#399]
### Background
While using the HTTP api to call the endpoint "/v1/taproot-assets/assets/meta" i get the error "message: '/taprpc.TaprootAssets/FetchAssetMeta: unknown permissions required for method"

### Steps to reproduce

```ts
const macaroon  = "macaroon";
const agent = new https.Agent({ rejectUnauthorized: false });

const response = await get("/v1/taproot-assets/assets/meta", {
      params: {
        asset_id,
        meta_hash,
      },
      baseURL: `https://host:port`,
      httpsAgent: agent,
      headers: {
        "Grpc-Metadata-macaroon": this.macaroon,
      },
    })
```
### Expected behavior
Get the metadata

### Actual behavior

got the error message: '/taprpc.TaprootAssets/FetchAssetMeta: unknown permissions required for method

**Comment by guggero** [comment]
Probably just a missing entry in the permissions map in the RPC server.

**Comment by ffranr** [comment]
> Probably just a missing entry in the permissions map in the RPC server.

@guggero It's there on master: https://github.com/ffranr/taproot-assets/blob/9c8d7b106711be0fd1cf7179825d87afe5163e9c/perms/perms.go#L79-L79

It's been there since may.

@sidahmedabdelillah which commit are you working with please? Consider using the latest on master.

**Comment by sidahmedabdelillah** [comment]
i was using the release  "tapd v0.2.0-alpha" i will try with a newer release and update. Thank you

**Comment by guggero** [comment]
Any update on this? Can we close the issue?
