### ISSUE TITLE
proof: add a set of magic bytes to the serialized proof file format

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#402]
In order to easily detect if a blob is a proof file (has the version header, etc), or just a single state transition, we should add a set of magic bytes, similar to what `sqlite` does: https://www.sqlite.org/fileformat.html#magic_header_string

All serialized proof files then _must_ start with this value, and it can make distinguishing between raw files and a state transition easier. Related to #401 

[Edit] Summarized task list:

- [ ] Update binary encoding of proof files and proof transitions to include the prefix
- [ ] Update all test vectors and unit test data
- [ ] Update the `DecodeProof` RPC to detect the format and decode it accordingly
- [ ] Go through all RPC methods and fields that accept or return proofs and make it very clear if it's a file or an individual proof

**Comment by guggero** [comment]
In addition to adding a prefix (I'd vote for `0x54 0x41 0x50 0x50` => `TAPP` for a single proof and `0x54 0x41 0x50 0x46` => `TAPF` for a proof file), we should go through the RPC interface and add a comment (and possibly rename fields where necessary) to make it more clear whether a field contains (or expects) a file or a single proof.

Summarized task list:

- [ ] Update binary encoding of proof files and proof transitions to include the prefix
- [ ] Update all test vectors and unit test data
- [ ] Update the `DecodeProof` RPC to detect the format and decode it accordingly
- [ ] Go through all RPC methods and fields that accept or return proofs and make it very clear if it's a file or an individual proof
