### ISSUE TITLE
[tracking]: Backport protocol updates to BIPs

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#430]
## Todo

- [x] #437
  - @ffranr PR https://github.com/Roasbeef/bips/pull/37
- [x] #438
  - @guggero PR https://github.com/Roasbeef/bips/pull/38
- [x] Test vectors
  - @guggero PR https://github.com/Roasbeef/bips/pull/39

**Comment by dstadulis** [comment]
# TODO

- [ ] Robyn's PR https://github.com/Roasbeef/bips/pull/37
- [ ] Oli will need to add a PR

**Comment by guggero** [comment]
@Roasbeef I created two more BIP PRs, see list above.

**Comment by Roasbeef** [comment]
Resolved with the merge of the final PR. 

I think only action items here are to track the population of some of the place holder test vectors.
