### ISSUE TITLE
Add proof courier address field to Tap address

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#434]
A Tap address should include a mandetory proof courier address. 

The receiving node during the asset send procedure could use this new field to contact a proof courier service and retrieve proof(s) associated with then send event.

In other words: In order to receive and asset, the receiver generates a tap address. That tap address will contain a proof courier address. The sender submits the transfer proof to that proof courier. Which the receiver can then retrieve.

This new field should support multiple proof courier protocols:
```
universerpc://the.host.name:port
hashmail://mailbox.server:port
```

This is a prerequisite to https://github.com/lightninglabs/taproot-assets/issues/344

**Comment by ffranr** [comment]
Related PR: https://github.com/lightninglabs/taproot-assets/pull/432

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/taproot-assets/pull/450.
