### ISSUE TITLE
[enhancement]: improve QueryAssets sorting

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/taproot-assets#436]
### Background

The `QueryAssets` RPC allows you to sort results using the `sort_by` parameter. This always returns results in ascending order. For Terminal, we would like to allow users to also sort in descending order so that the user can see the assets with the most syncs first.

In addition, the AssetQuerySort enum is missing an option to sort by the asset's `total_supply`.

### Your environment

```sh
# tapcli getinfo                                    # version of `tapd`, `lnd`, and network
{
    "version":  "0.2.3-alpha commit=v0.2.3",
    "lnd_version":  "0.16.4-beta",
    "network":  "regtest"
}

# uname -mrsv                                          # operating system 
Linux 5.15.49-linuxkit-pr #1 SMP PREEMPT Thu May 25 07:27:39 UTC 2023 aarch64

# bitcoind --version || btcd --version # version of `btcd`, `bitcoind`, or other backend
Bitcoin Core RPC client version v24.0.1
```

### Steps to reproduce

View the testnet `QueryStats` REST url:
https://testnet.universe.lightning.finance/v1/taproot-assets/universe/stats/assets?sort_by=SORT_BY_TOTAL_SYNCS

### Expected behavior

I should be able to provide an additional parameter to the query string specifying if I want the results sorted ascending or descending. This could be a boolean flag named `descending` or `reverse`. It could also be an enum called `sort_direction` with values `SORT_DIRECTION_ASC` or `SORT_DIRECTION_DESC` with ascending being the default.

I should also be able to specify a new `SORT_BY_TOTAL_SUPPLY` value for the `sort_by` parameter.

### Actual behavior

There is no way to sort the results by most syncs first.

**Comment by Roasbeef** [comment]
SGTM, seems straight forward enough with our SQL integration.

**Comment by dstadulis** [comment]
### Issue deliverables
- [ ] Sort results in ascending or descending ordering.  Using either:
  - [ ] Boolean flag named descending or reverse
  - [ ] enum called `sort_direction` with values `SORT_DIRECTION_ASC` `SORT_DIRECTION_DESC` (`sort_direction=SORT_DIRECTION_ASC` as default)
- [ ] Add new `SORT_BY_TOTAL_SUPPLY` value to `sort_by` parameter

**Comment by Roasbeef** [comment]
@ben2077 is taking a look at this

**Comment by ben2077** [comment]
https://github.com/lightninglabs/taproot-assets/pull/485
