### ISSUE TITLE
Generalise proof query/insert RPC endpoints to support transfer proofs

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#439]
Generalise proof query and insert RPC endpoints such that they support transfer proofs. They currently only support issuance proofs.

The RPC endpoints are called `QueryProof` and `InsertProof`.

This change will include storing transfer proofs within the multiverse.

Deliverables:
- [ ] Delete code reference in this comment https://github.com/lightninglabs/taproot-assets/issues/439#issuecomment-1672304820
- [x] #467

**Comment by Roasbeef** [comment]
So right now the RPC interface doesn't make a distinction between them. The only area we gate things is here: https://github.com/lightninglabs/taproot-assets/blob/70774640f868988f8c5aa6eb7c977c6e9a105bf1/universe/base.go#L199-L205

**Comment by ffranr** [comment]
I've renamed this issue and changed the description but the actual work won't deviate from what we've planed for this sprint.

**Comment by ffranr** [comment]
Addressed here: https://github.com/lightninglabs/taproot-assets/pull/473
