### ISSUE TITLE
Rename header verifier to block verifier.

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#442]
The header verifier doesn't just verify the block header. It also verifies the block height. We should rename it to `blockVerifier` for clarity.

This is the header verifier generator: https://github.com/lightninglabs/taproot-assets/blob/a4b3c0693da97faf76c92c58f20b2ee675b0f105/tapgarden/caretaker.go#L1027

**Comment by Roasbeef** [comment]
> We should rename it to blockVerifier for clarity

It doesn't verify blocks. It verifies a header, and that the header is in the main change at the target block height. 

I think we can close this?
