### ISSUE TITLE
Sender node encourages user to update node when encountering unsupported proof courier address protocol

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#455]
As a first step in sending an asset, the receiver node generates a tap address. The address contains a proof courier service address (which is used in transferring proofs related to the send procedure).

The proof courier address includes a schema/protocol specifier. We must assume that a particular version of the tap daemon can only support a subset of all possible proof courier address protocols. (Later tap daemons could support protocols that earlier daemons do not.)

We need to design a means of selecting/negotiating a viable proof courier protocol based on the capabilities of the receiver and sender nodes.

**Comment by Roasbeef** [comment]
> We need to design a means of selecting/negotiating a viable proof courier protocol based on the capabilities of the receiver and sender nodes.



I don't think the sender+receiver would have an interactive session to communicate that. This is why the potential defaults (and also the eventual sync feature of cross multiverse instances) are important.

**Comment by guggero** [comment]
I agree that we probably don't need to handle that. If the receiver is on an old version, then the sender should be fine. If the sender is on an old version and doesn't understand the address protocol, then I think an error message along the lines of "unknown proof courier protocol <proto> in address, please update your tapd" should be fine.

**Comment by ffranr** [comment]
> If the sender is on an old version and doesn't understand the address protocol, then I think an error message along the lines of "unknown proof courier protocol in address, please update your tapd" should be fine.

I'll update this issue's title to reflect that this is the work to be done.

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightninglabs/taproot-assets/pull/497
