### ISSUE TITLE
Fallback: Support encoding multiple proof courier addresses in single Tap address

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#461]
It is currently possible to encode a single proof courier address in a Tap address (implemented here: https://github.com/lightninglabs/taproot-assets/pull/450). This issue is about extending that capability such that we can include a secondary fallback proof courier address within a Tap address.

This enhancement might come in handy if we find that proof courier services are frequently flaky.

**Comment by dstadulis** [comment]
Alternatively if #498 is implemented, this feature wouldn't be necessary.

**Comment by dstadulis** [comment]
> Alternatively if #498 is implemented, this feature wouldn't be necessary.

@ffranr can you confirm if #461 can be closed, as it seems #498 is completed

**Comment by ffranr** [comment]
This issue isn't adding much at all given what we've merged.
