### ISSUE TITLE
[enhancement]: Validate proof courier address based on URI scheme/protocol

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#462]
We should validate a proof courier address based on the URI scheme/protocol. This might matter, for example, in that some protocols don't require a port to be specified.

Source: https://github.com/lightninglabs/taproot-assets/pull/450#discussion_r1300727495

**Comment by dstadulis** [comment]
would enable proof delivery through multiple delivery protocols

hashmail
HTTPS
?nostr

Robyn said this might be need to bring into sprint because the work could take part in #344

**Comment by ffranr** [comment]
This is currently in place. See for example: https://github.com/ffranr/taproot-assets/blob/main/proof/courier.go#L142-L160
and how the `CourierAddr` interface (and address as a struct) facilitates the address validation flow.
