### ISSUE TITLE
Add multiverse/universe service asset-specific config

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#476]
A multiverse service operator should be able to include or exclude specific assets from its database. This issue tracks an enhancement that will include adding multiverse service configuration functionality to that effect.

A new SQL table should be added which serves to manage a list of assets that should be exclusively included in the service's multiverse. We should add a CLI command and RPC endpoints for inserting, deleting, and listing assets in that table.

*Will add more details later today...*

**Comment by Roasbeef** [comment]
Related to #444

**Comment by Roasbeef** [comment]
Levels: 
  1. only want issuance for an asset 
  2. only want issuance for any relevant asset 
  3. want transfers for an asset 
  4. want errthing

**Comment by Roasbeef** [comment]
Also has implications for sycning as well: 
  * Once you get past option 3, can't use existing syncing flow 
     * Instead, need to do a vanilla set diff, and base it on that, can use other hash commitment or key structure to save on work.

**Comment by Roasbeef** [comment]
For CLI can just have: 1 and 2 available.

**Comment by ffranr** [comment]
Spun off issuance sync work into this issue: https://github.com/lightninglabs/taproot-assets/issues/524
