### ISSUE TITLE
Remove RPC endpoint `AssetRoots` in favour of `QueryAssetRoots`

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#494]
Endpoint `AssetRoots` returns all known universe roots where as endpoint `QueryAssetRoots` returns a single universe root (even though the endpoint name has "Roots" plural) for a given target asset (group).

We should extend the capability of `QueryAssetRoots` such that it returns all known universe roots if a target asset (group) is not specified. And then we can retire `AssetRoots`.

**Comment by Roasbeef** [comment]
Not sure I follow: `AssetRoots` is used to return the set of all roots, while `Query` is used to find the root for a specific asset. Not sure we need to over engineer at this present state before we have more usage to guide the evolution of the API.
