### ISSUE TITLE
Fallback proof courier addr points to LL universe RPC proof courier tapd node

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#498]
LL (Lightning Labs) currently runs a HashMail protocol proof courier service called Aperture. We use this service as a fallback courier service for use when an alternative proof courier address is not supplied (either via RPC parameter or CLI argument when starting tapd).

It's good that we run a proof courier because it serves as a fallback mechanism to ensure that peers can send proofs to one another. However, LL should run a unvierse RPC proof courier (universe RPC protocol) and the fallback proof courier address encoded in tapd should point to that service.

Work to complete:
* [ ] ensure universe RPC proof courier RPC endpoints can be accessed by the public (config via tapd flag)
* [ ] make the necessary ops changes to run a tapd node with publicly accessible universe RPC endpoints
* [ ] set tapd fallback address to that of the new service

**Comment by dstadulis** [comment]
Robyn thinks the scope of this can be limited to:
- writing into the universe and taking things out
Will need to asses the implication on proof decoding costs.

**Comment by Roasbeef** [comment]
This is done.
