### ISSUE TITLE
[testing]: Fuzz test user-input fields & Fix fuzzing crashes

### ISSUE THREAD

**Issue by Crypt-iQ** [lightninglabs/taproot-assets#502]
### Fuzzing user-input fields scope: @Crypt-iQ 
- [ ] addr
- [ ] Proof file parsing and verification 
- [ ] RPC inputs

### Fix known bugs discovered from fuzzing: @guggero 
1. OOM via allocations: https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/file.go#L176

2. OOM via allocations: https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/file.go#L187

3. OOM via allocations (use DecodeP2P if record sizes are < 65535): https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/proof.go#L295 causes this https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/encoding.go#L92

4. OOM via allocations: https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/encoding.go#L157

5. OOM via allocations: https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/encoding.go#L206

6. OOM via allocations (use DecodeP2P): https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/taproot.go#L205

7. OOM via allocations + underflow (l may be 0): https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/commitment/encoding.go#L176

8. OOM via allocations: https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/proof/tx.go#L144

9. OOM via allocations (use DecodeP2P): https://github.com/lightninglabs/taproot-assets/blob/c64acbeb27ae900dd5003cdf7caa6754d896996f/address/address.go#L361

**Comment by Crypt-iQ** [comment]
The fuzzer I used for addresses is here, but it's not in a ready state since I had to disable some bech32 checks: https://github.com/Crypt-iQ/taproot-assets/tree/address_fuzzer

**Comment by jharveyb** [comment]
We have similar patterns in the `fn` package FWIW. Not sure if we should have two versions, one that does prealloc?
