### ISSUE TITLE
Add script-path validation unit tests for group_key witness scenarios

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#511]
@jharveyb to list issue deliverables

**Comment by jharveyb** [comment]
In descending priority order:

- [ ] Manually generate group witness with a non-empty tapscript root, and verify witness via normal minting flow
- [ ] Exercise new VM validation branches
- [ ] Exercise group and group anchor verifiers + sortassets
- [ ] Coverage for `GroupPubKey()`, `DeriveGroupKey()`, and new Has/NeedsGenesisWitnessForGroup helpers
- [ ] Exercise new branches in `proof.Verify()` concerning group key validation
- [ ] Validate group key reveal handling in `committedProofs()`
- [ ] Validate store & load of multi-element group witnesses

**Comment by jharveyb** [comment]
Mostly address by https://github.com/lightninglabs/taproot-assets/pull/598, further plans detailed in 549.

**Comment by jharveyb** [comment]
May have an issue validating when the meta field was empty on the CLI.
