### ISSUE TITLE
Implement backoff procedure in universe proof courier

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#512]
The hashmail proof courier uses a backoff procedure to re-attempt proof transfer if an attempt fails. We should use a similar procedure in the universe proof courier.

This change involves abstracting the backoff functionality from the hashmail proof courier and then using it in the universe proof courier.

**Comment by Roasbeef** [comment]
Keeping this open, as we still need receiver back off.

**Comment by dstadulis** [comment]
Receiver side will land by EoD Monday
SQL tables will be changed and scope is complete

**Comment by ffranr** [comment]
We should add an itest for the universe proof courier which is similar to `testOfflineReceiverEventuallyReceives`.

**Comment by dstadulis** [comment]
objective is to get the PR in now and then add test in `v0.3.2`
