### ISSUE TITLE
Isolate Universe syncing to only issuance proofs

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#524]
Currently, where universe syncing is concerned, tapd supports syncing all proof types only. It is not currently possible to sync only issuance proofs.

The method we use to sync involves comparing MS-SMT root hashes. If they match then there is no need to sync any leaves. If they do not match then we compute a leaf diff set and insert leaves as appropriate.

We should design a sync methodology suitable for issuance only universe trees.

**Comment by Roasbeef** [comment]
I think a simple carve out would be having the leaf query response have a `bool` if it's an issuance leaf. Then the sync just skips those items. Arguably, you still want to actually decode to check if it's actually issuance or not.

**Comment by ffranr** [comment]
I think we should add a `IssuanceOnly` flag to the `AssetLeafKeys` RPC endpoint.
