### ISSUE TITLE
[feature]: add support for int64 ids to tapdb

### ISSUE THREAD

**Issue by positiveblue** [lightninglabs/taproot-assets#533]
### Background
Currently we use the `postgres` [engine](https://github.com/lightninglabs/taproot-assets/blob/main/sqlc.yaml#L3) to generate the boilerplate db code with `sqlc`.

To keep compatibility between sqlite and postgres we write "the most standard" sql code and make some changes in the table definitions when running a migration in postgres.

One of those changes are translating `INTEGER PRIMARY KEY` to `SERIAL PRIMARY KEY`.

This has a couple of effects that we may want to fix:
- Sqlite is using int64 for storing the ids while postgres is using int32 
- In postgres, we have 31 bits before overflowing (~2.147B)

31 bits may be more than enough. If we do 10 inserts per second, we will have `864000` new rows per day and it will take us almost 7 years to hit the type limit. I do not know if it makes sense to tackle this problem, but the next two sections show the current state in detail and a possible fix.

### Current setup

```
CREATE TABLE IF NOT EXISTS myTable {
    id INTEGER PRIMARY KEY
}
```

**SQLite behaivour**: `INTEGER PRIMARY KEY` is autoincremetnal and it's stored as `int64`.
**PostgreSQL behaivour**: `INTEGER PRIMARY KEY` is substituted by `SERIAL PRIMARY KEY` which is auto-incremental and stored as `int32`
**SQLC go code**: `INTEGER PRIMARY KEY`, with the postgres engine is translated as `int32`

### Proposed solution

**Objective: autoincremental int64 ids**
 
```
CREATE TABLE IF NOT EXISTS myTable {
    id BIGINT PRIMARY KEY
}
```
**SQLite behaivour**: `BIGINT PRIMARY KEY` *IS NOT* autoincremetnal in sqlite. It is also stored as `int64`. We would substitute it for `INTEGER PRIMARY KEY`
**PostgreSQL behaivour**: `BIGINT PRIMARY KEY` is substituted by `BIGSERIAL PRIMARY KEY` which is auto-incremental and stored as `int64`
**SQLC go code**: `BIGINT PRIMARY KEY`, with the postgres engine is translated as `int64`

**Comment by Roasbeef** [comment]
https://github.com/lightningnetwork/lnd/pull/7357/commits/0c1ffbabb1b80c0cac874de7d02ea58df1902119
