### ISSUE TITLE
[bug]: assets send status blocking at ADDR_EVENT_STATUS_TRANSACTION_CONFIRMED

### ISSUE THREAD

**Issue by nostrassets** [lightninglabs/taproot-assets#552]
### environment
polarlightning/tapd:0.2.3-alpha
polarlightning/lnd:0.17.0-beta

### Steps to reproduce
1. create a addr to receive assets : tapcli addrs new --asset_id
```sh
tapcli addrs new --asset_id
```
2. send assets to the addr that generated by step1: 
```sh
tapcli assets send --addr (generated by step1)
```
3. cal cmd : tapcli assets receives --addr (generated by step1)
```sh
 tapcli assets receives --addr (generated by step1)
```
Result : 
```sh
docker exec -it -u tap alice-tap tapcli --rpcserver {host} addrs receives --addr taptb1qqqsqq3qt43uc0638z2x9hzf4lvv9ghg07xhwexymr0hgukpd4clapmzph2sgggz6utjl9mf3z4u0kknumnmc6jjj9wsnd47600f47wgaysnnmdvlf2qvggzpu8qg0xasc68t3rzkn9tty42njremnsjdvg29acunrwvzljxwjassqth5p4wpf
{
    "events":  [
        {
            "creation_time_unix_seconds":  "1696556559",
            "addr":  {
                "encoded":  "taptb1qqqsqq3qt43uc0638z2x9hzf4lvv9ghg07xhwexymr0hgukpd4clapmzph2sgggz6utjl9mf3z4u0kknumnmc6jjj9wsnd47600f47wgaysnnmdvlf2qvggzpu8qg0xasc68t3rzkn9tty42njremnsjdvg29acunrwvzljxwjassqth5p4wpf",
                "asset_id":  "5d63cc3f51389462dc49afd8c2a2e87f8d7764c4d8df7472c16d71fe87620dd5",
                "asset_type":  "NORMAL",
                "amount":  "119",
                "group_key":  "",
                "script_key":  "02d7172f976988abc7dad3e6e7bc6a52915d09b6bed3de9af9c8e92139edacfa54",
                "internal_key":  "020f0e043cdd863475c462b4cab592aa9c879dce126b10a2f71c98dcc17e4674bb",
                "tapscript_sibling":  "",
                "taproot_output_key":  "9d0a79dded72e041464efdcf358a0e25cc6e31e3679905fd914fbdd1ffc427ea"
            },
            "status":  "ADDR_EVENT_STATUS_TRANSACTION_CONFIRMED",
            "outpoint":  "36dbdf8c8259503cf868eb42e40d2a41fdaf197c9ecbe585297b374b043800d8:1",
            "utxo_amt_sat":  "1000",
            "taproot_sibling":  "",
            "confirmation_height":  2530439,
            "has_proof":  true
        }
    ]
}
```
Check on chain, the tx has been finished for a long time.
https://mempool.space/testnet/tx/36dbdf8c8259503cf868eb42e40d2a41fdaf197c9ecbe585297b374b043800d8

**Comment by nostrassets** [comment]
Here is the log of tapd : 
2023-10-06 08:40:40.002 [ERR] RPCS: [/universerpc.Universe/QueryAssetStats]: verification failed: signature mismatch after caveat verification
2023-10-06 08:40:50.042 [ERR] RPCS: [/universerpc.Universe/QueryAssetStats]: verification failed: signature mismatch after caveat verification
2023-10-06 08:41:00.061 [ERR] RPCS: [/universerpc.Universe/QueryAssetStats]: verification failed: signature mismatch after caveat verification
2023-10-06 08:41:10.006 [ERR] RPCS: [/universerpc.Universe/QueryAssetStats]: verification failed: signature mismatch after caveat verification

And background:
1. The daemon has a domain name. ===> taro.xxx.com
2. The daemon port is 12029 not 10029

**Comment by nostrassets** [comment]
I restart the tapd daemon , the problem is fixed.

**Comment by guggero** [comment]
> I restart the tapd daemon , the problem is fixed.

Okay, good to know. As mentioned, this will be more robust in the upcoming `v0.3` release. Closing the issue as this has already been addressed.

**Comment by dstadulis** [comment]
Thanks for the report
