### ISSUE TITLE
cmd/lncli: make new CLI commands for the universe federation config commanda 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#566]
New protos here: https://github.com/lightninglabs/taproot-assets/pull/563.

**Comment by jharveyb** [comment]
From offline discussion:

-CLI args should take precedent over config from file or config stored in DB.
-Need some way to flag or resolve config conflicts directly (what if config file and DB differ on startup?)
-May want to expose only a subset of options via CLI

**Comment by jharveyb** [comment]
Resolved with #568
