### ISSUE TITLE
tapgarden/rpc: expose custom sighash flags for vPSBT funding to enable trustless asset swaps

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#577]
### Background 

Today, we have the [vPSBT API](https://lightning.engineering/posts/2023-06-14-virtual-psbt/) which allows users to do custom spends using assets the daemon owns. Those custom spends can also have their own scripts, and also eventually custom sighash flags as well. Due to the unique nature of the TAP overlay, flags that normally are considered useless, like `SIGHASH_NONE`, are actually of use for _non-interactive_ swap scenarios. In this case, a seller can publish some data, and the "first" (subject to fee bidding, etc) buyer to add enough funds is able to claim those assets. 

#### The "One Little Trick" 🪄

The missing component to enable this today is allowing users to sign on the _TAP_ level with custom sighash flags. We also want to expose users bringing their own PSBT as well. Once this is exposed, `SIGHASH_NONE` can be used to sign "blank checks" (on the TAP layer). However, these blank checks cannot be cashed without also spending the input that encumbers the check input. That input can only be spent by completing a Bitcoin input/output "puzzle", by adding enough extra inputs to pay the seller and make the check claim valid. This process is non-custodial, and non-interactive 😎. 

### Sally The Seller's Signed Offer

Here's an example flow to illustrate the concept: 
  1. Sally decides to part with her 1-of-1 holographic beefzard card gifted to her by her grandpa so she can make a down payment on a condo in the new SpaceX Luna base. 
  2. She has an input `X`, that commits to the beefzard card (and nothing else for simplicity of this example). 
  3. She makes a PSBT (Bitcoin layer) that adds input `X`, and then an output with a bip 86 addr (doesn't commit to any assets). This 1-in-1 out input is signed with `SIGHASH_SINGLE | SIGHASH_ANYONE_CAN_PAY`. The output asks for `1 BTC` on top of the input amount.
       * At this point, the transaction isn't valid. The transaction is missing that 1 BTC input. 
  4. Sally now makes a vPSBT for the output that the buyer will use to claim the beefzard card. This vSPBT output is "loose", in that everything known is specified, but it doesn't commit to a script key, nor internal key. 
  5. Sally _signs_ (or w/e valid witness for the beefzard card) that vOutput, with `SIGHASH_NONE`. This means she doesn't commit to the script key the asset is to be sent to. This is where some of the magic happens. 
  6. Sally publishes her signed PSBT, and also the signed vPSBT. 
       * The only way someone can claim this is to:
            * Provide enough input to pay Sally. 
            * Anchor the vPSBT output into a new output under the control of the buyer. 

### Claiming the Swap Offer On-Chain

For someone to claim this:
   1. They see the offer from Sally on Nostr, or w/e.
   2. They add in their input on the Bitcoin level to complete the transaction. 
   3. They take the vOut, and anchor it in their new output, providing their own script key and internal key
   4. Broadcast, ???, profit.
      * Here ??? means they may need to compete in the mempool with the other would-be buyers. 

### Interactive & Non-Interactive Auctions 

To eliminate the ???, Alice can set up an open auction. She suspends her beefzard in a timelocked output (only needs to be on the TAP layer), then she has others send her offers, which come in the form of the 1-in-1 out described above. She can run things like a dutch auction using the `sequence` field of the execution transaction: as the price descends, so does the sequence field. Initially, only the highest price is available, then as time goes on, the lower prices are us available and unencumbered by the relative time lock.

You can make the process non-interactive again by publishing these time locked orders as outlined above.

**Comment by lukegao209** [comment]
"Today, we have the vPSBT API which allows users to do custom spends using assets the daemon owns"
does vPSBT API  means this api ?
/v1/taproot-assets/wallet/virtual-psbt/sign

**Comment by ben2077** [comment]
It seems that initially, we need to implement SIGHASH for vPSBT. However, can we use 'universe' as a topic for P2P message distribution, and under this topic, these kinds of transactions enter into a subtopic, akin to an auction room? There are a series of conditions before entering this room, such as the timeout duration of the auction, and so on. By sharing an auction transaction mempool in this 'universe-room' manner, can we ultimately achieve a P2P transaction auction functionality based on TAPD?

**Comment by guggero** [comment]
> "Today, we have the vPSBT API which allows users to do custom spends using assets the daemon owns" does vPSBT API means this api ? /v1/taproot-assets/wallet/virtual-psbt/sign

There are currently three API endpoints that deal with virtual PSBTs:
```
/v1/taproot-assets/wallet/virtual-psbt/fund
/v1/taproot-assets/wallet/virtual-psbt/sign
/v1/taproot-assets/wallet/virtual-psbt/anchor
```

**Comment by Roasbeef** [comment]
@ben2077 

> However, can we use 'universe' as a topic for P2P message distribution, and under this topic, these kinds of transactions enter into a subtopic, akin to an auction room? 

I think instead, something like Nostr would be better suited, as you don't necessarily need to keep all this information around, particularly if not all messages result in an actual mach. But otherwise, yeah, it's feasible to make a system where you can exchange+bid+clear+execute all this in a p2p manner.

**Comment by Roasbeef** [comment]
Related to #118

**Comment by dstadulis** [comment]
Won't be huge just need to enable more than sighash all and then thread it through

**Comment by guggero** [comment]
The [PSBT BIP](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) already defines a `PSBT_IN_SIGHASH_TYPE = 0x03` type, so we can just make sure we look at that field when signing the vPSBT.

**Comment by dstadulis** [comment]
### Goal
- [ ] Draft PR by 2023-12-18

**Comment by dstadulis** [comment]
- [ ] Add unit tests to ensure sighash is being properly validated

**Comment by dstadulis** [comment]
Implementing:
- [ ] Right-sized output s.t. there’s no change
- [ ] Optimization: “Anyone can spend” clever trick
