### ISSUE TITLE
tapgarden/custodian: check the local proof archive/universe when looking to receipt proofs

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#578]
Today the custodian looks at the local proof archive (in the database and flat flies on disk) to figure out if it has the receipt proof it needs to spend received assets. It should also create a notification service that uses the local universe instance to detect if it has received proofs. This'll allow users to use `tapcli universe proofs insert` to grab proofs from w/e and insert locally. 

## Steps To Completion 

- [ ] Give the custodian a new multi archive wrapper that'll return inserted proofs at this point: https://github.com/lightninglabs/taproot-assets/blob/a990fdf18c2ca13cbb825c9aa95866831ccfadf8/tapgarden/custodian.go#L540-L551. 
- [ ] This should be allowed to short circuit the normal courier here: https://github.com/lightninglabs/taproot-assets/blob/a990fdf18c2ca13cbb825c9aa95866831ccfadf8/tapgarden/custodian.go#L403-L415.

**Comment by dstadulis** [comment]
Need to add another notifcation
