### ISSUE TITLE
mint+transfer: randomize anchor UTXO amounts

### ISSUE THREAD

**Issue by jharveyb** [lightninglabs/taproot-assets#579]
Right now we always mint assets with an anchor UTXO value of 1000 sats. This is an obvious round amount that does not need to be fixed.

A simple fix would be to pick an anchor value randomly from a small range like [1001, 1999]. This would still be quite obvious for large batch mints or transfers but better than round payment amounts.

**Comment by nostrassets** [comment]
Can I set it in v0.3?

**Comment by guggero** [comment]
> Can I set it in v0.3?

No, this wasn't implemented for v0.3 yet.

**Comment by dstadulis** [comment]
Closing in favor of https://github.com/lightninglabs/taproot-assets/issues/721
If a covertness privacy property is desired, randomization is suboptimal
