### ISSUE TITLE
Error running tapcli

### ISSUE THREAD

**Issue by Jeezman** [lightninglabs/taproot-assets#585]
### Background

- Installed and ran tapd successfully
- Ran `tapcli --network mainnet  assets mint --type normal --name fantasycoin --supply 100 --meta_bytes "fantasy money"`
- Gets the following error

```[tapcli] unable to mint asset: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"DESKTOP-JGHCT1F\")"```

### Your environment

```sh
tapcli getinfo                                    # version of `tapd`, `lnd`, and network
tapd version 0.3.0-alpha.rc2 commit=v0.3.0-alpha.rc2
lnd version 0.17.0-beta commit=v0.17.0-beta-98-gad5cd9c8b
network mainnet

uname -mrsv                                          # operating system 
Linux 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64

bitcoind --version || btcd --version # version of `btcd`, `bitcoind`, or other backend
Bitcoin Core version v25.99.0-52c6904c7891
```

### Expected behavior
tapcli commands should work as expected

### Actual behavior
tapcli commands not working as expected even `tapcli getinfo`

**Comment by guggero** [comment]
What port is `tapd` running on? Are you also running a `testnet` version of `tapd` on the same machine? Looks like the TLS certificate that is picked up by default doesn't match the one your `tapd` is serving. Do you get the same error if you try `tapcli --network mainnet --tlscertpath ~/.tapd/tls.cert ...`?

**Comment by Jeezman** [comment]
@guggero I'm running `tapd` on mainnet. My `tapd.conf` below

```sh
network=mainnet 
 
lnd.host=localhost:10009 
lnd.macaroonpath=~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon 
lnd.tlspath=~/.lnd/tls.cert 
 
tapddir=~/.taproot-assets 
 
rpclisten=127.0.0.1:10029 
restlisten=127.0.0.1:8089
```

Running `tapcli --network mainnet --tlscertpath ~/.tapd/tls.cert getinfo` 

gives the following error

`
[tapcli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"DESKTOP-JGHCT1F\")"`
