### ISSUE TITLE
rpc: add pagination support to all relevant RPC APIs

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#590]
Today we have pagination support for some calls like the `QueryAssetStats` call. We should also add them where relevant to the set of other calls that can return lists of data. 

One example is the `QueryAssetRoots` and `AssetLeafKeys` call. Eventually both of these will exceed the default gRPC message limit, so we need to add pagination support here to ensure syncing, etc can still work.

**Comment by Roasbeef** [comment]
For the leaf keys and the leaves, we should either have pagination be based on the block height, or sort in the query before we send things over.

**Comment by GeorgeTsagk** [comment]
> One example is the QueryAssetRoots and AssetLeafKeys call. Eventually both of these will exceed the default gRPC message limit, so we need to add pagination support here to ensure syncing, etc can still work.

Here I guess you refer to the [`AssetRoots`](https://github.com/lightninglabs/taproot-assets/blob/main/taprpc/universerpc/universe.proto#L14) rpc call? That's the one that fetches all the roots for all known assets

[`QueryAssetRoots`](https://github.com/lightninglabs/taproot-assets/blob/main/taprpc/universerpc/universe.proto#L20) returns info about a specific asset

**Comment by guggero** [comment]
Correct, `AssetRoots` is the most important one. With `QueryAssetStats` following second, as that also allows to pull a lot of info in just one call.
