### ISSUE TITLE
universe: implement topological sort for syncing from the universe transfers tree

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#591]
Today when we client is configured in "full sync" mode (so issuance and transfer trees for any or all assets), we'll run into an issue (dependent on the key sorting) where we'll fail to insert a transfer proof into our local universe. 

When we go to validate the inputs for a transfer proof, we'll try to fetch all the inputs so we can get the amt+script for each of them: https://github.com/lightninglabs/taproot-assets/blob/e695071f24be98c845b898eff811d58c57d4ed5a/universe/base.go#L198-L212

The `getPrevAssetSnapshot` routine will then attempt to fetch the leaf proofs from the local multiverse:
https://github.com/lightninglabs/taproot-assets/blob/e695071f24be98c845b898eff811d58c57d4ed5a/universe/base.go#L436-L452

If we're validating the transfer of asset `X`, _before_ the issuance of asset `X`, then this will fail. 

To resolve this, when we're syncing items from a Universe, if we're syncing the transfer root, then we need to make sure we do a _topological sort_ of the leaves before we attempt to validate them. In order to stage the items during sync, a set to build up the set of relevant leaves. Then we'll validate them in chunks, based on the set of disjointed graph for an input cluster, using topological sort to validate them in order.

**Comment by jharveyb** [comment]
Continuation of https://github.com/lightninglabs/taproot-assets/pull/592#discussion_r1361638607 :

I think we could extend the proof file format to include the # of proofs, and then also sort with that.

Once processing is sorted we could also deduplicate some proof verification (if I'm verifying a spend, and a spend of some outputs from the first spend, then these proof files would only differ by one proof).

**Comment by dstadulis** [comment]
Fixed in #594 https://github.com/lightninglabs/taproot-assets/pull/594/commits/6cc83003a7989b016fc7795fd1a04f2a2d97759c
