### ISSUE TITLE
[bug]: Unable to burn asset and at the same time I lose all units of that asset

### ISSUE THREAD

**Issue by kulisekf** [lightninglabs/taproot-assets#599]
### Background

I tried to burn a certain amount of asset units (always < 100%). After executing the burn command output, this asset completely disappeared from the tapcli assets list, but the asset record in tapcli assets balances and tapcli universe roots are still fully populated.

### Your environment

tapcli getinfo   
```json
{
    "version":  "0.3.0-alpha.rc2 commit=",
    "lnd_version":  "0.16.3-beta",
    "network":  "testnet3"
}
```
uname -mrsv   
```
Linux 5.4.0-164-generic
```
bitcoind --version || btcd --version  
```
Bitcoin Core version v24.0.0
```
lsb_release -a
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
```

### Steps to reproduce

First I minted asset type normal. 
`tapcli assets mint --type normal --name fantasycoin --supply 100 --meta_bytes "fantastic money"`
`tapcli assets mint f`
tapcli assets list:
[assets_list_before_burn_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999368/assets_list_before_burn_output.txt)

after mining several blocks is time for burn
`tapcli assets burn --asset_id {asset_id} --amount 50`
output:
```
Please confirm destructive action.
Asset ID: 23a7f87be15b96427286d2bf0c4960b7f3bff2c713792ad728818e5f93b82de7
Current available balance: 100
Amount to burn: 50
 Are you sure you want to irreversibly burn (destroy, remove from circulation) the specified amount of assets?
Please answer 'yes' or 'no' and press enter:
```
I entered `yes`
output:
[burn_command_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999362/burn_command_output.txt)

### Expected behavior

Maximum amount of the asset will be reduced, I will lose the same amount along with it, but I will have access to the rest

### Actual behavior
log:
[log_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999377/log_output.txt)

tapcli universe roots | grep -A 4 -B 9 fantasycoin:
[universe_roots_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999387/universe_roots_output.txt)

tapcli assets transfers:
[assets_transfers_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999389/assets_transfers_output.txt)

tapcli assets list:
[assets_list_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999396/assets_list_output.txt)

tapcli assets list --show_spent:
[assets_list_show_spent_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999398/assets_list_show_spent_output.txt)

tapcli assets balance:
[assets_balance_output.txt](https://github.com/lightninglabs/taproot-assets/files/12999477/assets_balance_output.txt)

note: these command outputs are when the burn transaction has at least 3 confirmations in the chain

**Comment by kulisekf** [comment]
same result. I deleted the .tapd and ran the latest version -> `tapcli getinfo`:
```json
{
    "version": "0.3.0-alpha.rc3 commit=",
    "lnd_version": "0.16.3-beta",
    "network": "testnet3",
    "lnd_identity_pubkey": "032c6698ed356a4b64faebe989e162399a5450af58f73dca41a80be3ee05f57e5a",
    "node_alias": "MyLightningKul",
    "block_height": 2533901,
    "block_hash": "0000000000000037ef124df2f6de6c85cda18b529999a857ce83eac6c0c217fe",
    "sync_to_chain": true
}
```
the procedure I subsequently carried out was completely identical to the one I described above. I am attaching txt files with outputs, obtained in the same way as above and at the same time named the same for better clarity (daemon started with `--debuglevel=trace`)

[assets_balance_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011285/assets_balance_output.txt)
[assets_list_before_burn_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011288/assets_list_before_burn_output.txt)
[assets_list_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011290/assets_list_output.txt)
[assets_list_show_spent_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011292/assets_list_show_spent_output.txt)
[assets_transfers_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011294/assets_transfers_output.txt)
[burn_command_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011296/burn_command_output.txt)
[log_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011298/log_output.txt)
[universe_roots_output.txt](https://github.com/lightninglabs/taproot-assets/files/13011300/universe_roots_output.txt)

**Comment by guggero** [comment]
Thanks a lot for the detailed documentation! I was now able to reproduce and a fix is on its way: https://github.com/lightninglabs/taproot-assets/pull/600
