### ISSUE TITLE
Is there any way to get txhash when call FinalizeBatch by rpc?

### ISSUE THREAD

**Issue by nostrassets** [lightninglabs/taproot-assets#606]
### Background
When call FinalizeBatch by RPG API,  BatchKey and other response will be returned,
but there is no txhash.

Can FinalizeBatch API return the txhash?
or is there any way to get the txhash by the FinalizeBatch

**Comment by ffranr** [comment]
The `FinalizeBatch` RPC endpoint returns a data structure which contains the field `BatchTxid`. The value of this field is the string representation of the batch transaction hash. See here: https://github.com/lightninglabs/taproot-assets/blob/c7d57c597dfaadf0732a9ffb4bf63152c427f8f8/rpcserver.go#L2330-L2330

Is that what you were looking for @nostrassets ?

**Comment by nostrassets** [comment]
should be this one ,but it does't exist in the api response. 
https://lightning.engineering/api-docs/api/taproot-assets/mint/finalize-batch

**Comment by nostrassets** [comment]
@Roasbeef @ffranr  is the feature in v0.3.0? 
Will it be include in next tag?

**Comment by ffranr** [comment]
The field was added here: https://github.com/lightninglabs/taproot-assets/commit/6bcc9b42cf004580b26e62683ebf9631714243ea

Which occurred after the last `v0.3.0-alpha` tag. The field is available on the `main` branch. It will be included in the next tag. I'm not sure when we will tag next.

**Comment by Roasbeef** [comment]
Implemented here: https://github.com/lightninglabs/taproot-assets/pull/603 

Next tag should be sometime next week.
