### ISSUE TITLE
[bug]: tapd can not start when lnd compiled from the main/master branch

### ISSUE THREAD

**Issue by oneforalone** [lightninglabs/taproot-assets#607]
### Background

I'm just using lnd which build from source for tapd service, however, the tapd cannot start, and keep complaining the following error:

```
error creating server: unable to connect to lnd node: error checking connected lnd version. at least version "v0.15.99, build tags 'signrpc,walletrpc,chainrpc,invoicesrpc'" is required
```

However, i'm just compile lnd from the latest source codes, and it still the same error. And after tried start from the release bin file, 
it success without any error, and then i compare the difference between the lnd binary, and it turns out the latest `lnd` version is: `lnd version 0.17.0-beta commit=tor/v1.1.3-36-g15f421379` and the binary release `lnd`'s version is `lnd version 0.17.0-beta commit=v0.17.0-beta`. So, the tapd is just checking with the commit, not the version, that's kind mis-leading.

### Your environment

It just related to latest lnd install from source.
```sh
lnd --version
lnd version 0.17.0-beta commit=tor/v1.1.3-36-g15f421379
```

### Steps to reproduce

1. Install `lnd` from source:
```sh
git clone https://github.com/lightningnetwork/lnd
cd lnd
make install
```
2. start `lnd`
3. start `tapd` , then you may got the same error.

### Expected behavior

It should work with the latest lnd build from source. Or, in another words, it should work with any commits if the version is greater than v0.15.99 with build tags 'signrpc,walletrpc,chainrpc,invoicesrpc'.

### Actual behavior

The LND version check did not pass if the commits not match, even if LND's version is satisfied.

**Comment by guggero** [comment]
This isn't an issue with the version. You need to specify the required build tags (when running `make install`) as mentioned here: https://github.com/lightninglabs/taproot-assets/blob/641f31c8bc5987a52dba2b4f2a27caddfa4a144c/README.md#prerequisites

**Comment by oneforalone** [comment]
It's the same error with or without `tags="signrpc walletrpc chainrpc invoicesrpc"` arguments, i believe the main reason is that you only check with the version commit's or maybe it's hash.
