### ISSUE TITLE
postgres: expose config to tune the max number of connections

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#619]
We default to 25 by default right now, we should look into tuning this value: https://github.com/lightninglabs/taproot-assets/blob/c7d57c597dfaadf0732a9ffb4bf63152c427f8f8/tapdb/sqlite.go#L32

**Comment by guggero** [comment]
We can overwrite the default by using `--postgres.maxconnections`.

**Comment by guggero** [comment]
Not needed, config already exists.

**Comment by guggero** [comment]
We might want to be able to configure the [idle connections and lifetime](https://github.com/lightninglabs/taproot-assets/blob/main/tapdb/postgres.go#L75-L82) as well.

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/taproot-assets/pull/622.
