### ISSUE TITLE
addrs: attempt to sync from universe if asset ID unknown 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#620]
As a we move away from the global sync config, we want to make UX more streamlined, by attempting to query for the main root before error'ing out to the user that we don't know of the asset ID.

**Comment by jharveyb** [comment]
Need to double check the timeout for universe fetches, we may want a lower timeout here.

Leaning towards adding this logic to the `NewAddr` call instead of the `address.Book` to avoid adding universe-specific context to the Book that right now only needs to have a DB handle and access to the KeyRing.

Should be straightforward to cover in itest by excluding assets in the initial universe sync of the second node.

**Comment by ffranr** [comment]
We can probably accomplish this without code logic changes. We need to set the federation sync global config and the asset specific federation sync configs. We need to set the asset specific federation sync configs at address creation and then synchronously sync before returning an address.

I discussed this with Oli today. We should probably all jump on a call later to make sure we're all on the same page.

**Comment by jharveyb** [comment]
Updating the config as well makes sense to me - but I think this becomes problematic in the case of grouped assets.

Given other in-flight changes, a client would not sync issuance proofs for all grouped assets known to the Universe server. This means existing client-side checks for if an asset is grouped would fail, as the group itself was never imported during Universe sync.

One possible solution would be a new RPC where a client queries a Universe with a Universe ID (made with only the asset ID), the Universe does a group membership check, and returns the Universe ID for that asset's group, if that asset is grouped. 

With the correct Universe ID, the client would then be able to sync all leaves for that group and import the group info as usual.

**Comment by Roasbeef** [comment]
> Given other in-flight changes, a client would not sync issuance proofs for all grouped assets known to the Universe server. This means existing client-side checks for if an asset is grouped would fail, as the group itself was never imported during Universe sync.

I don't follow this. It's already the case right now that addrs are specific to an asset ID. Or do you mean being able to get a group key from the asset ID? 

Even in that case, I think it's fine to just have it work well for asset IDs, then for others, people need to go and manually sync it. 

Or we can just add the group key back to the addr, then they can use that for syncing.

**Comment by jharveyb** [comment]
For handling group keys, one option is to add an explicit `group_key` field to the `NewAddr` RPC, and avoid adding new means to look up a potential asset group.

Another option is to modify `QueryAssetRoots` to try and look up a group for the given asset ID, if no universe root was found. This should already be available from the `rpcserver` via `TapAddressBook.QueryAssetGroup`.
