### ISSUE TITLE
rpc: add `anchor_point` to the `QueryAssetStats` endpoint 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#641]
Today for the `QueryAssetStats` endpoint, we return the `genesis_point `, and `genesis_height` and `genesis_timestamp`. The `genesis_point` is the outpoint of the first input in the transaction that created an asset. The `genesis_height` is the height of the block that included the transaction, and the `genesis_timestamp` is the timestamp in the block header for that block. 

Some UIs were confused about `genesis_point`: they thought it was the output that created the asset. To clarify this, we should add `anchor_point`, which'll be the outpoint of the transaction that created the asset. We can get this information from the `genesis_assets` table, as we already return the `output_index`, so the query juts needs to obtain the `txid` of that anchor transaction.

**Comment by dstadulis** [comment]
checked in with @GeorgeTsagk and everything is ready for the PR to go
