### ISSUE TITLE
Custodian should emit an RPC notification status event when the recieve process completes sucessfully

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#650]
The custodian handles receiving assets. It should emit an RPC notification status event over the subscribers channel which is initialised via the RPC endpoint `SubscribeReceiveAssetEventNtfns`. This feature was requested by a user on slack [here](https://lightningcommunity.slack.com/archives/C03B3556HQ8/p1698818230588589).

Currently, the custodian does emit events emanating from the proof courier. This is an example of an event notification sent to subscribers:
https://github.com/lightninglabs/taproot-assets/blob/1e24b9997431cb14786550109292b8d6c90525c0/proof/courier.go#L704-L704

The new event should implement the `fn.Event` interface. It should contain (as fields) the corresponding address by which the asset was sent.

The new event should be emitted at this point: https://github.com/lightninglabs/taproot-assets/blob/1e24b9997431cb14786550109292b8d6c90525c0/tapgarden/custodian.go#L459-L459

**Comment by dstadulis** [comment]
Would like to consider what other event notifications could be added that may be helpful applications to use

**Comment by ffranr** [comment]
> Would like to consider what other event notifications could be added that may be helpful applications to use

A user on Slack requested an event notification which would be published once a sufficient number of confirmation block had been mined. (Confirming an asset transfer.)

**Comment by dstadulis** [comment]
How about just subscribe to confirmation count or reporting when the tap client meets it's "confirmed" threshold
