### ISSUE TITLE
Ensure we don't confuse the double hash of a transaction with it's txid

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#656]
In some instances we've confused the double hash of a transaction with the transaction ID (`txid`). I think this is one example: 
https://github.com/lightninglabs/taproot-assets/blob/e6b0516c681abcf88e27d02da076bcd7f34e6b51/rpcserver.go#L1383-L1383

There may be others. 

This confuses users because they can't use the "txid" as to look up a transaction in a mempool explorer.  I think we should check our other uses of transaction hash and transaction ID.

I've created this PR in `btcd` to help make our code clearer: https://github.com/btcsuite/btcd/pull/2055

**Comment by dstadulis** [comment]
itest might be the location for the text to be added

**Comment by ffranr** [comment]
I am aware of `chainhash.Hash.String()`, but I still think this PR is a good idea.

This PR makes it clear what `txid` is in relation to `MsgTx`. It isn't clear that `chainhash.Hash.String()` is `txid`. And it isn't necessarily always `txid` because `chainhash.Hash` doesn't have to be a double sha256.

**Comment by ffranr** [comment]
If we are to use `string` for `txid` then we should probably rename SQL field `chain_txns.txid` to `tx_hash`. This field is a blob and we currently set it to the tx hash.

**Comment by ffranr** [comment]
With the exception of the db change I mention in [this comment](https://github.com/lightninglabs/taproot-assets/issues/656#issuecomment-1799648228), this issue will be redundant once we complete https://github.com/lightninglabs/taproot-assets/issues/654
