### ISSUE TITLE
[feature]: Enable sending of multiple different assets with one send transaction

### ISSUE THREAD

**Issue by rkedez** [lightninglabs/taproot-assets#670]
**Is your feature request related to a problem? Please describe.**

When sending assets, all Taproot Asset addresses must be of the same asset ID (see e.g. [code comment in rpcserver.go](https://github.com/lightninglabs/taproot-assets/blob/main/rpcserver.go#L1994)). Therefore, sending many assets would necessitate making many BTC on-chain transactions with infeasibly high transaction costs.

**Describe the solution you'd like**

Ideally, I would like to send many different unique assets (e.g. 100k collectibles) with one send transaction and, respectively, one BTC on-chain transaction. When I asked about this feature on Slack some time ago, @guggero suggested that it involves anchoring multiple vPSBTs into a single transaction for which everything should be in place.

**Comment by ffranr** [comment]
tapd currently supports anchoring one vpsbt only, see: https://github.com/lightninglabs/taproot-assets/blob/76bb5ae01fc0aa147233f332c468943f8c47b053/rpcserver.go#L1750-L1750

I'll make an issue to enable multi vpsbt anchoring. I don't think an issue currently exists for that.
