### ISSUE TITLE
[bug]: Can't transfer assets: unknown sqlite error: SQL logic error: no such column: anchor_txid (1)

### ISSUE THREAD

**Issue by snow884** [lightninglabs/taproot-assets#685]
### Background

Describe your issue here.

### Your environment

```sh
tapcli getinfo                       # version of `tapd`, `lnd`, and network
```

```
{
    "version": "0.3.1-alpha commit=v0.3.1-21-gb8a007d",
    "lnd_version": "0.16.2-beta",
    "network": "testnet3",
    "lnd_identity_pubkey": "0332c0638eddcc313465ad993b482d290619f5b029dc9d3f0bdd9f83f12b27ead5",
    "node_alias": "0332c0638eddcc313465",
    "block_height": 2539030,
    "block_hash": "0000000000000023bd649f64a75eb30d6fe4c4b794d947fea8eb16d5619c142f",
    "sync_to_chain": true
}
```

```
uname -mrsv                          # operating system 
```

```
Linux 6.1.27-43.48.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May  2 04:53:36 UTC 2023 x86_64
```

```
bitcoind --version
```

```
Bitcoin Core version v22.0.0
```

### Steps to reproduce

1.) Mint assets on the old version of tapd

2.) Try sending assets on the new version of tapd
Resulting error:
```
[tapcli] unable to make addr: rpc error: code = Unknown desc = unable to make new addr: unable to make address for unknown asset 53b929739ef4db7554b484071999f59d7d74e935584fcc98005b581b427e0c9d: unknown sqlite error: SQL logic error: no such column: anchor_txid (1)
```
### Expected behavior

Successful transfer of assets

### Actual behavior

I get an error

**Comment by snow884** [comment]
I think this relates to this change 
https://github.com/lightninglabs/taproot-assets/issues/655

**Comment by GeorgeTsagk** [comment]
Hey @snow884 

This change was meant to be a backwards-breaking change.
Do you mean that an asset minted before `v0.3.1` cannot be transfered between two nodes of version `v0.3.1`?

Or are you trying to send to a `v0.3.1` from a `v0.2.0` ?

**Comment by dstadulis** [comment]
>1.) Mint assets on the old version of tapd
@snow884 which version was that?

**Comment by jharveyb** [comment]
I think this is related to the new optimistic address sync added for 0.3.1, based on the error text "unable to make address for unknown asset".

I think the previous PR, #655 , updated a struct that is used in a few queries unrelated to the main changes in that PR. That could have eadded an assumption about the anchor_txid being present for all of those queries.

For the optimistic sync, we may have an ordering issue where the anchor_txid fetched from sync isnt inserted before a query that now depends on it being present; I'm pretty sure it should be fetched as part of sync itself.

**Comment by Roasbeef** [comment]
I think I found the culprit: https://github.com/lightninglabs/taproot-assets/pull/667/files#diff-8cf5eeb60ca2af1641b4c2bed03452e02cddb689663027d180c65ee1ad170b07L318 

The change modified the existing migration definition, when it needs to drop the view in a new migration and re-create it.
