### ISSUE TITLE
[bug]: Typo in batch state: BATCH_STATE_PEDNING should be BATCH_STATE_PENDING

### ISSUE THREAD

**Issue by alex-georgiou** [lightninglabs/taproot-assets#690]
### Background

Not really a bug, more of a typo. But it can create confusion.

`BATCH_STATE_PEDNING` should be `BATCH_STATE_PENDING`.

I found this typo in at least [three places in the code](https://github.com/search?q=repo%3Alightninglabs%2Ftaproot-assets%20BATCH_STATE_PEDNING&type=code).

Since the software is still alpha, perhaps you could fix this without worrying about compatibility issues with other software.

### Your environment

```
tapcli version 0.3.0-alpha commit=v0.3.0
tapd version 0.3.0-alpha commit=v0.3.0
```

**Comment by GeorgeTsagk** [comment]
Hey @alex-georgiou 

Yes this typo was probably originally made in `mint.proto` and after compiling the rpc bindings it propagated into the code :)

Thanks for flagging this
