### ISSUE TITLE
bug: `AssetLeaves` RPC endpoint should return all proof types if argument proof type is unspecified

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#697]
Currently, if the proof type argument for the `AssetLeaves` RPC endpoint is unspecified, no proof leaves are returned. This is because a proof lookup is performed for a universe that does not exist (a universe which corresponds to the unspecified proof type).

The `AssetLeaves` RPC endpoint should return both issuance and transfer proofs if the proof type argument is left unspecified. This is what users expect and what would be most useful.

This issue was reported by a user on Slack, see: https://lightningcommunity.slack.com/archives/C03B3556HQ8/p1700664670126429

We should also add a proof type sanity check to `universe.Archive.MintingLeaves`.

**Comment by Roasbeef** [comment]
> The AssetLeaves RPC endpoint should return both issuance and transfer proofs if the proof type argument is left unspecified. This is what users expect and what would be most useful.

IMO we should keep the current behavior. The client should know which type of proof it actually wants. They can also have this fall back logic as well. 

Returning all the leave for the asset regardless of proof type will make the pagination a bit more involved, and we'll need to modify those queries. 

As time goes on for popular assets, the amount of transfer proofs will also grow to be much greater than the amount of issuance proofs. From a pagination perspective: which one should come "first"?

**Comment by ffranr** [comment]
> As time goes on for popular assets, the amount of transfer proofs will also grow to be much greater than the amount of issuance proofs. From a pagination perspective: which one should come "first"?

I would think that the issuance proofs should come first if there are less of them and a user wanted both proof types. They might get a complete set of issuance proofs in the first page. More unlikely for transfer proofs.

But I agree with your idea that the proof type should be specified. Keeps things simpler. I think we should raise an error if the proof type isn't specified. I don't think we should make an assumption if unspecified and we need to choose some proof type. Do you agree @Roasbeef ?

**Comment by ZZiigguurraatt** [comment]
I agree that https://github.com/lightninglabs/taproot-assets/issues/701 is better than nothing, but I do think the behavior of `tapcli universe leaves` is inconsistent with your logic above because we have

`--proof_type value  the type of proof to show the leaves for, either 'issuance' or 'transfer' (default: "issuance")`

I feel like we should either apply https://github.com/lightninglabs/taproot-assets/issues/701 to the CLI or make the `AssetLeaves` RPC have the same default as the CLI. As it is right now, if someone tests their query with the CLI and then just tries to pass the same arguments to the raw RPC, they won't get the same result.

**Comment by ZZiigguurraatt** [comment]
As another point of reference, if I use [QueryAssetRoots](https://lightning.engineering/api-docs/api/taproot-assets/universe/query-asset-roots/) and I leave `proof_type` not defined when I create `ID`, it defaults to `PROOF_TYPE_ISSUANCE`.
