### ISSUE TITLE
[bug]: release script version checker does not support alpha release candidates

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#709]
Fix the release script version checker such that it supports alpha release candidates.

@guggero explains:

> the problem in the script is only with RC version. because we attempt to match the version.go version of v0.3.2-alpha.rc2 against the git tag v0.3.2-rc2 which doesn't match. For non-RC version it would be v0.3.2-alpha against v0.3.2 which is a valid substring

Release script path: `./scripts/release.sh`

**Comment by dstadulis** [comment]
Issue should be triaged again -- might have been fixed with subsequent release.sh updates
