### ISSUE TITLE
[doc]: Document version-tagging specification

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#715]
**Is your feature request related to a problem? Please describe.**
Problem:
As a `taproot-asset protocol developer` I would like to `have a document specifying the git tag standard` in order to `ensure that tags are conformant to various downstream needs` such as the version-checking script and regex matches.  This specification would be in addition to https://semver.org/
[edit] @ffranr found this helpful site, as referenced in #720 
https://jubianchi.github.io/semver-check/#/version/0.3.2-alpha.2

It would be helpful to avoid mistakes or reloading all the context and requirements each time a release is performed and instead document the requirements.

**Describe the solution you'd like**
A document, added to the repo, specifying what the required form of git tags are to use for:
* Releases
* Release candidates
* Alternative releases

**Describe alternatives you've considered**
Not documenting the standard and spending time each release recalling them.

**Comment by ffranr** [comment]
Closed in favour of https://github.com/lightninglabs/taproot-assets/issues/729
