### ISSUE TITLE
[feature]: Custodian should emit an RPC notification status event when the recieve process starts

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#739]
The custodian should emit an RPC notification status event when the receive process starts. The event should be published to subscribers once a wallet transaction has been successfully associated with an address. Which happens here:

https://github.com/lightninglabs/taproot-assets/blob/7c0688e3bf84c2b9aeb4be3417cc766706ddaba7/tapgarden/custodian.go#L392-L392

Note that we already publish a transaction complete event to subscribers, see completed issue https://github.com/lightninglabs/taproot-assets/issues/650 .

This is where the custodian publishes that transaction complete event:

https://github.com/lightninglabs/taproot-assets/blob/7c0688e3bf84c2b9aeb4be3417cc766706ddaba7/tapgarden/custodian.go#L497-L497

This feature was requested on Slack: https://lightningcommunity.slack.com/archives/C03B3556HQ8/p1702546986057129

**Comment by RajGoodF** [comment]
Yes much needed !

**Comment by dstadulis** [comment]
## Receive-notification feature, acceptance criteria

tapd would emit a receive event
1. After a transaction has been initiated even if  the transaction hasn't yet been included in a block.
2. After the transaction is included in a block
3. After the block the transaction had been included in, is ejected from main chain. (reorged out)
