### ISSUE TITLE
proofs: change FetchProof in asset store to also look at outpoint

### ISSUE THREAD

**Issue by guggero** [lightninglabs/taproot-assets#745]
### Background

Within our asset store database we currently assume script keys to be unique across assets in some cases.
But when receiving to the same TAP address multiple times, the `AssetStore.FetchProof` would currently fail because multiple items would be returned for the `FetchAssetProof` SQL query.

**Comment by jharveyb** [comment]
Resolved?

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/taproot-assets/pull/730.
