### ISSUE TITLE
[bug]: impossible to know if a proof is an issuance proof

### ISSUE THREAD

**Issue by straumat** [lightninglabs/taproot-assets#750]
### Background

After discussing on slack with @guggero we thought we could determine if a decoded proof is an issuance proof with the rule `prev_id.anchor_point === "000000....00000:0"`.

### Your environment

taplcli build from on 22 december. 

### Steps to reproduce

I have a proof file in the attached file: [decodeProof-proofFile3-proofAtDepth0-withoutMetaReveal-request.json](https://github.com/lightninglabs/taproot-assets/files/13756751/decodeProof-proofFile3-proofAtDepth0-withoutMetaReveal-request.json).

I call decode with `proof_at_depth = 0`, I get:
```
"decoded_proof": {
    "proof_at_depth": 0,
    "number_of_proofs": 3,
    ...
    "prev_witnesses": [
        {
          "prev_id": {
            "anchor_point": "0000000000000000000000000000000000000000000000000000000000000000:0",
            "asset_id": "0000000000000000000000000000000000000000000000000000000000000000",
            "script_key": "000000000000000000000000000000000000000000000000000000000000000000",
            "amount": "0"
          }
    ...
}
```
I call decode with `proof_at_depth = 1`, I get:
```
decoded_proof": {
    "proof_at_depth": 1,
    "number_of_proofs": 3,
    ...
    "prev_witnesses": [
        {
          "prev_id": {
            "anchor_point": "632d0c3935fff230aa3718e268dce5517786d7976f7aa33efb615b408737b0ad:0",
            "asset_id": "e16029acc4d2cf0505857265442344efb5547f2047a3fc1c4822683f7c57820e",
            "script_key": "023a8d9bc352eb3f5f69b798a941f06244b3633a8fd2cf82406132504ff08e23ff",
            "amount": "0"
          }
    ...
}

```

I call decode with `proof_at_depth = 2`, I get:
```
"decoded_proof": {
    "proof_at_depth": 2,
    "number_of_proofs": 3,
    ...
    "prev_witnesses": [
        {
          "prev_id": {
            "anchor_point": "0000000000000000000000000000000000000000000000000000000000000000:0",
            "asset_id": "0000000000000000000000000000000000000000000000000000000000000000",
            "script_key": "000000000000000000000000000000000000000000000000000000000000000000",
            "amount": "0"
          }
    ...
}

```

So it seems I can't use `prev_id.anchor_point === "000000....00000:0"` as a way to know if a decoded proof is an inssurance proof.

### Expected behavior

Seems `prev_id.anchor_point === "000000....00000:0"` should be only in one decoded response ?

**Comment by Roasbeef** [comment]
So an issue proof (the very first proof that created the asset) will only have a proof depth of 1. There'll only be a single proof, and that final proof will have the all zero anchor point. 

On the API, there's a flag that you need to set to ensure that prev witnesses actually get decoded: `with_prev_witnesses`. Some assets will also have a `genesis_reveal` present if they were created with a group key.

**Comment by straumat** [comment]
Thanks.
I thought there could be a proof or proof file not containing the issuance proof, that's why i wanted to know if there was a way to know if a proof is an issuance proof. 
For now, I was calling the decode method with meta_reveal... if i had an error code, i would call the decode method without meta_reveal... It's not a great solution.

**Comment by guggero** [comment]
Thanks for the file provided, that helped. I took a look and the issue is that the last asset in the file (`"proof_at_depth": 2,`) is the result of an asset split. So you have to also check whether `prev_witnesses[x].split_commitment` is set.

So basically the following rules:

```
prev_id.anchor_point === "000000....00000:0" && split_commitment == null --> genesis asset

prev_id.anchor_point === "000000....00000:0" && split_commitment != null --> split send

prev_id.anchor_point !== "000000....00000:0" --> full value send

```
