### ISSUE TITLE
[bug]: streamline event completion on custodian reboot / start up

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#781]
### Background

send-complete events that have occurred while tapd is offline aren't ever reported as completed

### Steps to reproduce

Untested observation from inspecting goroutines with @ffranr 

### Expected behavior

send complete events that have occurred after tapd comes back online after being offline

https://github.com/lightninglabs/taproot-assets/blob/1ca17f6faa8edcaccd7e5e3d7c4d638f8ca2c988/tapgarden/custodian.go#L279-L285

This commit contains TODOs that relate to streamlining receive event completion: https://github.com/lightninglabs/taproot-assets/pull/773/commits/b07b74f21dfd275aa78d3be5200800930151ae48

**Comment by ffranr** [comment]
Another change that we should make at the same time is to change this into a `>` rather than a `==`:
https://github.com/lightninglabs/taproot-assets/blob/1ca17f6faa8edcaccd7e5e3d7c4d638f8ca2c988/tapgarden/custodian.go#L445

The confirmations field can be negative, uses signed integer type.
