### ISSUE TITLE
tapgarden: earlier handling of asset script keys

### ISSUE THREAD

**Issue by jharveyb** [lightninglabs/taproot-assets#820]
Requirement for #722.

When issuing an asset into a group, we need to produce a valid group witness. Right now the only option is a signature with the group key itself, over a virtual TX that represents the asset genesis. This requires the assets in the batch to be fully-formed, with a genesis point for the batch selected and a script key derived.

Right now, asset script keys cannot be provided by the user, and they are always BIP86 keys. The user also cannot specify a genesis point for the batch. We derive a group key right after setting these fields in an asset.

To use a custom group key witness, we would need to have the asset fully-formed earlier, and expose the virtual TX representing the asset genesis to a user for them to produce a valid group witness.

Specifically:

- [ ] Add new options when submitting  a `MintAsset` request, to also specify a script key.
- [ ] Derive script keys for asset seedlings when they are submitted, before the batch is frozen.
- [ ] Derive internal keys for asset groups when seedlings are submitted, before the batch is frozen (or accept external keys as the internal key for a group key?)
- [ ] Select the genesis outpoint earlier when freezing the batch (or when creating a batch?)
- [ ] Expose the virtual TX for grouped asset genesis to the user, perhaps via the `ListBatches` RPC?
- [ ] Modify `ListBatches` and other RPCs to always represent seedlings in a batch in insertion order, so that users can provide witnesses in the same order.
- [ ] Accept group witnesses for assets in a batch, likely as part of the `Finalize` call.

**Comment by jharveyb** [comment]
From offline discussion, we definitely need to move funding for the batch earlier, as the asset ID for each asset in the batch depends on the funding input used (the genesis point) for the batch. So we'll need to fund the batch as soon as it's created, which is when a seedling is submitted and no batch already exists.

This makes manual feerates a bit more complicated, but coin selection changes on the LND may allow us to add another input if needed when the batch is being finalized.

**Comment by Roasbeef** [comment]
> From offline discussion, we definitely need to move funding for the batch earlier, as the asset ID for each asset in the batch depends on the funding input used (the genesis point) for the batch

The alternative to doing this would be to instead add another step in the RPC flow. So after `Add`, but before `Finalize`, you'd call `SupplyWitness` (or w/e). That would require less of an internal overhaul, but introduce a new step in the minting flow, only if you you're using a custom group key with a script path though.

**Comment by jharveyb** [comment]
There's a fair amount of update between this issue and #721.

From offline discussion + https://github.com/lightninglabs/taproot-assets/issues/721#issuecomment-1978636746:

Adding seedlings to a batch and funding the batch are separate; we probably want two new calls to modify the batch. One to define part of the onchain TX for the batch, `FundBatch`, and another to optionally submit custom witness for asset groups, `SealBatch`.

`FundBatch` should accept a PSBT, where advanced users can define a genesis input, and custom outputs which could include a custom batch internal key and amt of sats for the genesis output. `FundBatch` should also accept a tapscript tree root, as the sibling for the genesis tap commitment. Without a supplied PSBT, we can maintain the current behavior of calling `FundPsbt` with a single dummy output. A custom fee rate could also be set with this call.

Once a batch is funded, we can compute the asset ID and tweaked group key for all members of the batch. This allows advanced users to compute custom witnesses for group issuances.

`SealBatch` should accept or produce all asset-level witnesses needed for the batch, and result in a fully formed (but unsigned at the anchor level) PSBT that commits to the batch. Since all assets have their final asset IDs set, custom witnesses can be mapped to assets by asset ID. We can also validate custom witnesses at this point.

`Finalize` would now have no extra arguments, and instead just sign the anchor input and handle TX broadcast.

To mimic the current minting workflow (input selection from backing LND wallet, no custom witnesses), we could have `SealBatch` call `FundBatch` if the batch is not funded, and have `Finalize` call both `FundBatch` and `SealBatch` if witnesses are missing (and the minter can produce witnesses for all asset groups + the genesis input).

For this issue, I'll add these new calls but not add user-supplied PSBT support, as that can be split into a follow-up PR.

**Comment by jharveyb** [comment]
One new question here is around `FundBatch` and `SealBatch` behavior if called multiple times; if the first call succeed, should the second call mutate the batch or reject the request and instruct the user to cancel and resubmit the batch?

E.x. I create a batch of a few assets, call `FundBatch`, and it succeeds. If I call `FundBatch` again, maybe to adjust the feerate, we could:

- 'Unwind' the old funding inputs, fund the batch, and then overwrite the batch TX.
- Detect that the batch is already funded and return an error.
- Do something else, like adjust the feerate with the existing input if possible, or update the associated anchor tapscript sibling.

As-is, `SealBatch` should always fail if the batch is not yet funded. Calling `FundBatch` after a successful `SealBatch` call would invalidate all the existing asset groups, so at that point I think it makes sense to just return an error and request batch resubmission.
