### ISSUE TITLE
[feature]: Specify UTXOs as Parameters in Asset Send API

### ISSUE THREAD

**Issue by lukegao209** [lightninglabs/taproot-assets#825]
Reason:
Our operations sometimes need specific UTXO management
such as

generating more UTXOs to reduce waiting times on-chain,
managing balances through different UTXOs for Virtual Accounts
and more...

https://lightning.engineering/api-docs/api/taproot-assets/taproot-assets/send-asset

**Comment by jharveyb** [comment]
Did you mean asset UTXOs, BTC UTXOs, or both? Right now I think this can be done, but requires using the vPSBT interfaces / RPCs.
