### ISSUE TITLE
[feature]: add and make use of `fn.Result` type

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#832]
I think we should add a Rust style `Result` type, see: https://doc.rust-lang.org/std/result/enum.Result.html

This should let us do
```golang
func foo() fn.Result[Response] { ... }
```

And then use it as follows

```golang
result := foo()
if err := result.Err(); err != nil { ... }

response := result.Unwrap()
```
---

What's wrong with returning `(fn.Option[Response], error)`? Well, the return value of `(fn.None, nil)` is often invalid. And I can't enforce that invalidity using a combination of `fn.Option` and `error`. Similarly for a return type of `(*Struct, error)`, the value `(nil, nil)` is often invalid. We check for `err != nil` but we don't always check the first value for non-nil.

**Comment by gijswijs** [comment]
Isn't there still the possibility of `result.Unwrap()` returning `nil`? I don't see how this fixes that.

**Comment by ffranr** [comment]
> Isn't there still the possibility of `result.Unwrap()` returning `nil`? I don't see how this fixes that.

Yes I think you're right. And I don't think there's a nice way around that. Oli mentioned that this would only change the semantics, and I think I agree.

**Comment by Roasbeef** [comment]
You can do `fn.Either[T, error]` and it's mostly the same. I tried it in some other projcts, but ergonomics need some improvements with helper functions. Nice thing tho, is then everything returns 1 value, so you don't need one for (`T`), then `(T, error)` or w/e. 

You can actually see a version of it here in lnd: https://github.com/lightningnetwork/lnd/pull/8520/files#diff-9736b9211432399f7c2884c7c8319a0f897f1e070ef1c66e00cbd4528b6b981eR72.
