### ISSUE TITLE
[bug]: restart tapd will reset  FedGlobalSyncConfig when with the --universe.public-access flag.

### ISSUE THREAD

**Issue by lukegao209** [lightninglabs/taproot-assets#839]
Start tapd with the --universe.public-access flag.
Modify the settings accordingly.
Restart tapd.
The FedGlobalSyncConfig will be reset to its initial values. And then tapd will cost a long time and cpu to sync assets from lightning labs's universe

To prevent this, I suggest implementing an initialization check in server.go. 

```
	if s.cfg.UniversePublicAccess {
		err := s.cfg.UniverseFederation.SetAllowPublicAccess()
		if err != nil {
			return fmt.Errorf("unable to set public access "+
				"for universe federation: %w", err)
		}
	}
```

**Comment by dstadulis** [comment]
Thanks for the report

>Restart tapd
When the tapd daemon is started for a second time (the restart), is the `--universe.public-access` flag being set?

**Comment by lukegao209** [comment]
yeah, --universe.public-access flag is being set.

**Comment by Roasbeef** [comment]
Ran into this myself, pretty annoying. 

Here's a suggestion on how to resolve this:
   * Separate the config for allowed actions to your own personal universe server vs how to _sync_ with a remote universe server. 
   * The existing args stay, these govern your own personal universe server. When you do `--universe.public-access`, this means that you let people both read from your server, and also insert new proofs into your server. 
       * By default with this, you _won't_ actively sync all records from a remote/default universe server.
    * We add a new set of flags to govern how _sync_ works. The default is sync nothing. You can add `--universe.sync-all-assets` to indicate you want to attempt to sync any universe root you can find. Today we have `import`, and `export`. This adds a third option: `sync`. 
    * In the auto syncer, when we go to sync, we'll look at this flag to see if it should be done at all. If so, then we look at the global or local flags to determine _what_ to sync.
