### ISSUE TITLE
[feature]: add support for RFQ price oracle RPC service

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#906]
We need to implement modifications related to the price oracle component of the RFQ service.

#### Modifications Required

1. **Command Line Flag `--rfq.acceptall`**
   - Add the command line flag `--rfq.acceptall`.
   - This flag is optionally specified on `tapd` startup.
   - When specified, the RFQ service will accept the peer-suggested rate tick during any RFQ negotiation. It will also accept any quote regardless of subject asset.
   - This should be a development flag and should be clearly indicated as such.

2. **Command Line Argument `--rfq.oracleurl`**
   - Add the command line argument `--rfq.oracleurl`.
   - This is an optional command line argument.
   - Users can specify a price oracle service URL using this argument.
   - The specified URL will be queried whenever the RFQ service needs to query a price oracle.
   - The price oracle URL must be an RPC service.

3. **Default Behavior**
   - If neither `--rfq.acceptall` nor `--rfq.oracleurl` are specified, the RFQ service should reject any RFQ requests.
   - Log a warning message indicating the lack of necessary configuration.

**Comment by ffranr** [comment]
Any solution to this issue will need to build upon this (currently open) PR: https://github.com/lightninglabs/taproot-assets/pull/904

**Comment by ffranr** [comment]
I think `--rfq.acceptall` should be a dev only flag. Should the flag be called `--dev.rfq.acceptall` or something like that? Is that a pattern that we use anywhere? And we can hide it behind the golang compile `dev` tag also.

**Comment by guggero** [comment]
Discussed offline:

 - Add ShouldAcceptBidPrice and ShouldAcceptAskPrice methods to price oracle interface, mock implementation just returns true
 - if --experimental.rfq.acceptallprices is set, we _don't_ call into the above methods
 - add a new flag --experimental.rfq.priceoracleaddress (should match rfqrpc://<hostname>:<port>)
   - if the flag is not set, then we use an implemetations of the price oracle mock
   - the static usd/asset price of the mock oracle can be configured with --experimental.rfq.oracleusdperbtc
   - if the flag is set and is a proper URI with the rfqrpc:// prefix, then we use that implementation
   - the Oracle RPC is defined in `taprpc/rfqrpc/oracle.proto` with a service called Oracle
 - the default value for --experimental.rfq.priceoracleaddress is empty, which results in an error ("must specify price oracle address)
 - to enable the mock, the user can use the static price oracle address of "use_mock_value_promise_to_not_use_on_mainnet"

**Comment by dstadulis** [comment]
`--experimental.rfq.acceptallprices` is akin to a "market buy" where the RFQ is short circuited.

"use_mock_value_promise_to_not_use_on_mainnet" the RFQ process is engaged and used in a context where the clients need to test processing some sort price value.

A later enhancement will be, which will target cost minimization / price reasonableness.  Price reasonableness can use querying a set of price oracles (asserting: Either the client is receiving some competitive price or they're being eclipsed) and/or assessing the amount of divergence from previous values.  To ensure competitive price discoverability, ensuring nodes which aren't necessary linked via a channel can exchange RFQs will be oportune.

**Comment by ffranr** [comment]
The price oracle's RPC endpoints can just be:
```proto

service PriceOracle {
    rpc QueryPrice (QueryPriceRequest) returns (QueryPriceResponse);
}

enum TransactionType {
    PURCHASE = 0;

    SALE = 1;
}

message Price {
    uint64 amount = 1;

    uint64 expiry_timestamp = 2;
}

message QueryPriceRequest {
    TransactionType transaction_type = 1;

    AssetSpecifier subject_asset = 2;

    uint64 subject_asset_amount = 3;

    AssetSpecifier payment_asset = 4;

    Price payment_amount_hint = 5;
}

message QueryPriceSuccessResponse {
    Price price = 1;
}

message QueryPriceErrResponse {
    string error = 1;
}

message QueryPriceResponse {
    oneof result {
        QueryPriceSuccessResponse success = 1;

        QueryPriceErrResponse error = 2;
    }
}
```

**Comment by ffranr** [comment]
Find below the new RPC endpoint. Please let me know if it requires any significant changes:

```proto


service PriceOracle {
    /* tapcli: `priceoracle ratetick`
    QueryRateTick queries the rate tick for a given transaction type, subject
    asset, and payment asset. The rate tick is the exchange rate between the
    subject asset and the payment asset.
    */
    rpc QueryRateTick (QueryRateTickRequest) returns (QueryRateTickResponse);
}

enum TransactionType {
    PURCHASE = 0;

    SALE = 1;
}

message RateTick {
    // rate is the exchange rate between the subject asset and the payment
    // asset.
    uint64 rate = 1;

    uint32 precision = 2;

    uint64 expiry_timestamp = 3;
}

message QueryRateTickRequest {
    // transaction_type indicates whether the transaction is a purchase or a
    // sale.
    TransactionType transaction_type = 1;

    // subject_asset is the asset to be priced for purchase or sale.
    AssetSpecifier subject_asset = 2;

    // subject_asset_max_amount is the maximum amount of the subject asset that
    // could be involved in the transaction.
    uint64 subject_asset_max_amount = 3;

    // payment_asset is the asset used for purchasing or receiving from a sale.
    AssetSpecifier payment_asset = 4;

    // rate_tick_hint is an optional suggested rate tick for the transaction,
    // used to provide guidance on expected pricing.
    RateTick rate_tick_hint = 5;
}

message QueryRateTickSuccessResponse {
    RateTick rate_tick = 1;
}

message QueryRateTickErrResponse {
    string error = 1;
}

message QueryRateTickResponse {
    oneof result {
        QueryRateTickSuccessResponse success = 1;

        QueryRateTickErrResponse error = 2;
    }
}

```

**Comment by ffranr** [comment]
This is complete following this merge: https://github.com/lightninglabs/taproot-assets/pull/926
