### ISSUE TITLE
[feature]: add version field to RFQ wire messages

### ISSUE THREAD

**Issue by ffranr** [lightninglabs/taproot-assets#908]
### [Feature]: Add Version Field to RFQ Wire Messages

**Description:**
Request For Quote (RFQ) wire messages should include version fields.

**Rationale:**
Versioning for these messages is important because they are passed between peers that may be running incompatible `tapd` versions. Version fields will allow flexibility to modify the contents of RFQ messages in the future. Each RFQ message's version should be incremented separately, allowing the reject message to remain at a low version number for longer. The reject message can then be used to cleanly reject unsupported message versions. 

**Modifications:**
- Most modifications should be restricted to the `rfqmsg` package.
- Extend the `Validate` method for each message data to check the version number. Unsupported version numbers should fail validation. Refer to this example [`Validate` method](https://github.com/lightninglabs/taproot-assets/blob/057880e788247bf1417596a34b420e2ca3159e29/rfqmsg/buy_request.go#L147).
- The version TLV field should be the first field in a message data TLV stream.
- The BLIP does not currently specify version fields for RFQ messages. Refer to the [BLIP document](https://github.com/Roasbeef/blips/blob/tap-blip/blip-tap.md#request-for-quote-tap_rfq). The BLIP should be updated.

**Alternative Strategy:**
An alternative to version fields is to increment the p2p message type integer (similar to LND "custom messages"), defining completely new and distinct wire messages. However, this strategy complicates rejection of future versions by older `tapd` nodes. Therefore, IMO, we shouldn't depending on p2p message types.

**Comment by dstadulis** [comment]
Thinking that this should be a bit field akin to verisonBits so RFQ version cross-compatibility can be more tailored between clients
