### ISSUE TITLE
bip-taro+assets+vm: remove group key duplication, add explicit verification 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/taproot-assets#91]
The original intent of the group key is to allow other assets to be nested under similar assets in the SMT itself. To ensure that this key doesn't collide with other assets [we _tweak_ the "plain" group key with some information unique to the asset and it's location in the chain](https://github.com/lightninglabs/taro/blob/16d56c1b6fbeee544bedda236d69cf33125dd760/asset/asset.go#L89). 

However today in the code, we _encode_ this tweaked key in the final TLV leaf. This means that verifiers aren't able to verify that the key was the result of a valid tweak. Instead, we should be encoding the _plain_ group key (called just [RawKey](https://github.com/lightninglabs/taro/blob/16d56c1b6fbeee544bedda236d69cf33125dd760/asset/asset.go#L270-L272) today). Then the verifiers should take that key, apply the tweak, and validate the final signature against this key. 

I can think of two ways we can do this:
   1. Encode the raw key above, then have all verifiers re-compute the tweaked key to use that properly everywhere 
   2. Have the genesis asset place the _plain_ key in the witness itself 

I personally like the second option as it has less downstream impact. One other bonus is that we'll be able to get rid of duplication across transfers: today we always encode the group key sig, but don't really need to. Instead, this only needs to be verified at the genesis asset (once again the sig can be passed in as witness). 

With the above changes, for a new asset that has a group key, the witness will be: `<plain_fam_pubkey> <sig>`. Which kinda looks like a `p2wkh` output. If the group key is present on the genesis asset (the tweaked key field), then verifiers should: verify the tweaked derivation, verify the msg sig against that key.

**Comment by dstadulis** [comment]
we need to make sure all parties have the keys they need with the tweaks to do proper validation

**Comment by dstadulis** [comment]
Issue goal: ensure family key cannot be collided with explicit verificaiton.

**Comment by dstadulis** [comment]
Capturing some design jam thoughts of how to Asset Group / Key family issuance authortization is handled:

>Rotating the Asset Group / family_key key itself would mean the top level key of all the commitments themselves change:

>Assess if tarod should treat the family key itself as another taproot output key. Then this way, a taro transaction author can do w/e multi-sig threshold, etc construction, in the script path.

This logic should be added to the PR fixing this issue. 

>"the genesis witness should satisfy the tweaked family key, which means either script path or keyspend (the way it is rn)"

**Comment by halseth** [comment]
Asset "family" renamed asset "group": #200

**Comment by halseth** [comment]
Related: #110

**Comment by halseth** [comment]
> I can think of two ways we can do this:
> 
> 1. Encode the raw key above, then have all verifiers re-compute the tweaked key to use that properly everywhere
> 2. Have the genesis asset place the plain key in the witness itself
> 
> I personally like the second option as it has less downstream impact.

I agree, 2 seems like the way. 

However, one complication I saw from implementing this is that in order to verify the leaf not having the tweaked group key available is that this much be retrieved from genesis. This again means that proof history naturally will be verified from genesis->end. Earlier one could choose to verify the history end->genesis (I think).

Not sure if that's a big deal, the full history has to be verified regardless.

**Comment by Roasbeef** [comment]
@halseth yeh I like the second option too, this also lets us easily generalize the group key to be just a taproot output key. This would mean the group key just needs to satisfy a keyspend or script path, which would allow it to be multi-sig thresholds or w/e else (musig2 as well, but script gives more options). 

Re this extension, I think we'd then modify the current group sig field on each of the assets to instead live within the witness for that newly created assets. So for the first instance of the group key, we want a genesis witness that's a keyspend of that key. For future instances where the group key is used to bind to another asset ID, the genesis witness would then once again be a valid witness for the _original_ group key (can once again be just a sig here). 

If we like the above, then we'd likely want to modify the actual _digest_ that ends up being signed. We can probably just re-use the existing virtual tx mapping, but this time the inputs are blank just like a coinbase transaction, and the outputs is the newly created asset.

**Comment by Roasbeef** [comment]
> However, one complication I saw from implementing this is that in order to verify the leaf not having the tweaked group key available is that this must be retrieved from genesis. This again means that proof history naturally will be verified from genesis->end. Earlier one could choose to verify the history end->genesis (I think).

Hmm, not 100% what you mean. here. That one needs to verify the genesis of the _original_ asset the created the group key in order to verify the future assets? That's to be expected. Or do you mean that if we move the group sig field to live only in the genesis transaction for that new witness, then people need the genesis to validate the asset itself? That was sort of the plan, as once we add the base universe boostrapping, then you always would boostrap the asset first (which is the genesis proof) before interacting w/ it in anyway.

**Comment by jharveyb** [comment]
I think the initial sig verification would actually happen on asset bootstrap and before ever receiving a proof, so shouldn't affect proof verification?

**Comment by halseth** [comment]
> Or do you mean that if we move the group sig field to live only in the genesis transaction for that new witness, then people need the genesis to validate the asset itself?

Yes, exactly. When receiving a proof file (which is a linear history of the asset I received) I had the option to verify the history in either order. 

If we remove the group key and sig from each transfer, we no longer have that option, since we need to start at genesis to retrieve the group key (I could be wrong, so please correct me).

This is most likely not a big problem, but one thing that comes to mind is that it gets harder to "checkpoint" the history at a point in time.

**Comment by dstadulis** [comment]
>If we remove the group key and sig from each transfer, we no longer have that option

@jharveyb and I had some design discussions where I brought up this trade off.  It seems that after time I could potentially cause unnecessary amount of computation that appears as if could be avoided.

**Comment by Roasbeef** [comment]
> If we remove the group key and sig from each transfer, we no longer have that option, since we need to start at genesis to retrieve the group key (I could be wrong, so please correct me).


You'd always want to start from genesis, just like validating that a header chain actually connects to the genesis block. Only once you verify the genesis asset can you actually verify everything else.

**Comment by jharveyb** [comment]
Maybe the bootstrapping info for a grouped asset could include the first asset of the group? So verify the first use of the group key, and then the current use.

**Comment by Roasbeef** [comment]
> won't we need to reference the original minting transaction somewhere?

Yeah, that'll be in the issuance proof you bootstrap from a Universe. You just need the first proof where the group key was created in the first place. With that you know the old supply (or count) and also the raw key. You can then fetch the other uses to them have access to the total supply/count, and know all the asset IDs that are relevant for a given group key.
