### ISSUE TITLE
[enhancement] Decide: Refactor `EncodeCustomRecords` RPC or Introduce New Payment-Specific RPCs

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#945]
I think so, yes. Or maybe not, given that with this it should be pretty easy to do the RPC calls in any language. I guess the question is: how much effort is it for the app devs to call 3 RPCs (buy/sell order, encode records, send payment) with the correct values vs. us threading all the payment and channel flags through some new RPC methods in tapd...

_Originally posted by @guggero in https://github.com/lightninglabs/taproot-assets/pull/919#discussion_r1627047819_

**Comment by Roasbeef** [comment]
Fixes https://github.com/lightninglabs/taproot-assets/pull/1048
