### ISSUE TITLE
[feature]: decimal display support pt. 2

### ISSUE THREAD

**Issue by jharveyb** [lightninglabs/taproot-assets#948]
Addressing #925 , continuation of #930 .

- [x] Only encode non-default (non-zero) precision values.
- [x] Reject mints if the existing JSON metadata is too big to add the precision field to, if precision was specified.
- [x] On reissuance, fetch the precision from the asset metadata (if possible) of the asset group anchor, and assert equality with the reissuance request.
-- "Precision should be fixed for all issuances in an asset group"
- [x] display new precision field on some (?) RPC responses
-- ListAssets, ListTransfers, and the address-related RPC calls

**Comment by dstadulis** [comment]
- [ ] Add guidance / explanation in documentation the rationale behind a decimal display / precision of four 
- [ ] Add recommended use of decimal display in documentation

**Comment by Roasbeef** [comment]
https://github.com/lightninglabs/taproot-assets/pull/1059 will fix the last two bullet points here
