### ISSUE TITLE
[bug] Refactor existing itest in tapd to cover a grouped asset

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#957]
As identified in #947:
              Main action item here: refactor the existing itest in `tapd` to use a grouped asset.

_Originally posted by @Roasbeef in https://github.com/lightninglabs/taproot-assets/issues/947#issuecomment-2176786747_

**Comment by GeorgeTsagk** [comment]
Closed by https://github.com/lightninglabs/lightning-terminal/pull/781
