### ISSUE TITLE
[feature]: MVP Price-Oracle Service Demonstration

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/taproot-assets#995]
**Is your feature request related to a problem? Please describe.**

As a `potential edge node operator` I want to `understand how tapd's price oracle calls interact with external services` in order to `have a conceptual stepping stone for how to build my fully fledged price proffering system`

**Describe the solution you'd like**
- Deliverable:
	- Bare-minimum code to `solicit price information`, of a `currency pair`, from a `price feed source`
	- The context being in the future users may build systems which digest multiple types of pairs from numerous sources (internal or external)
- Estimated size
	- 20 line Go or Python of a rough implementation

**Comment by ffranr** [comment]
I've added a basic example price oracle service here: https://gist.github.com/ffranr/9d18e8f122e25b4bb435365b30c31456
