### ISSUE TITLE
[bug]: itest psbt_test.go func testPsbtTrustlessSwap 

### ISSUE THREAD

**Issue by penglipeng666** [lightninglabs/taproot-assets#996]
I try to be independent  "testPsbtTrustlessSwap ", However, there was a problem with the parameter in the following place, and the proof file could not be queried. Finally, I found that there seemed to be a problem with the parameter:

```
bobScriptKeyBytes := bobScriptKey.PubKey.SerializeCompressed()
	sendUniProof(
		t, t.universeServer.service, bob, bobScriptKeyBytes, genInfo,
		mintedAsset.AssetGroup,
		logResp.Transfer.Outputs[0].Anchor.Outpoint,
	)
```

I changed "bobScriptKeyBytes" to "logResp.Transfer.Outputs[0].ScriptKey" and succeeded!
Here is the query configuration file. Why is it "bobScriptKeyBytes"?

**Comment by penglipeng666** [comment]
https://github.com/lightninglabs/taproot-assets/blob/main/itest/psbt_test.go

**Comment by guggero** [comment]
What's the error you get when you don't change `bobScriptKeyBytes` to `logResp.Transfer.Outputs[0].ScriptKey`?
The two keys should be the exact same one, so either should work. I just tried it locally (`make itest icase=trustless`) and it works with both keys.

**Comment by penglipeng666** [comment]
I get it, I simulated "A-B-A" completely, so "func DeriveKeys" twice. sorry to bother you.
But for a complete "swap", you should transfer "logResp.Transfer.Outputs[0].Anchor.Outpoint".
thank you

**Comment by penglipeng666** [comment]
![image](https://github.com/lightninglabs/taproot-assets/assets/44795722/cce32a25-05c8-4f93-b7af-860849848f73)
