### ISSUE TITLE
[bug]: Tapd fails to start if minter doesn't have funds

### ISSUE THREAD

**Issue by GeorgeTsagk** [lightninglabs/taproot-assets#999]
## Description

Currently if a batch is created and a funding is attempted but no sufficient funds are available, tapd will terminate with an error related to not enough funds being available.

Upon restarting this error will immediately surface again and stop the daemon from starting up normally. See logs below
```
            "error":  "unable to initialize RPC server: unable to start asset minter: unable to fund minting PSBT for batch: 
036d76af505d9443a303e8991b53a00f29199dd2aafba27e2f03112beebe0c1521 unable to fund psbt: unable to fund psbt: rpc 
error: code = Unknown desc = error selecting coins: fee 0.00007700 BTC on total output value 0.00014115 BTC",

```

## Solution

We could reduce this to just be an `ERR` level log, or revert the funding of the batch / cancel it

**Comment by jharveyb** [comment]
Cancel sounds reasonable since the node operator could fund the backing wallet and then resubmit; daemon def shouldn't shut down if funding fails, will look into downgrading overall severity of the error.
